### ISSUE TITLE
Add migration instructions

### ISSUE THREAD

**Issue by dreina-toast** [atomiks/tippy.js-react#102]
We upgraded from tippy-react 1.1.1 to 2.2.0 and realised some styles were slightly off. Looking at the errors we found some css files were not found and had to change the imports as follows.

```diff
- import 'tippy.js/dist/tippy.css?raw'
- import 'tippy.js/dist/themes/google.css?raw'
+ import 'tippy.js/index.css?raw'
+ import 'tippy.js/themes/google.css?raw'
```

We didn't find other upgrades needed to be done in our code, but there might be other use cases that require further changes.

Should there be a "Migrating from v1" section in the readme?

**Comment by atomiks** [comment]
You don't need to import the main CSS anymore -- the default import auto-injects it into `<head>`.  Themes still need to be imported etc. The 2.0.0 release mentions this but maybe it's not clear enough

**Comment by atomiks** [comment]
https://github.com/atomiks/tippy.js-react/releases/tag/v2.0.0

I've updated the `Breaking changes` section to be clearer. That release changelog is effectively the guide 😄 hopefully it's good enough?
