### ISSUE TITLE
Disabling tooltip should hide active instance

### ISSUE THREAD

**Issue by andrey-liventsev-ontarget** [atomiks/tippy.js-react#106]
If tooltip is opened and isEnabled value has been changed to false then tooltip must be hidden.

See example:
https://codesandbox.io/s/interesting-aryabhata-lsju9
Steps to reproduce:
- Focus on button while it is enabled - tooltip is shown
- Wait for 2 sec, state has been changed to isEnabled: false
- Tooltip is still visible 
Expected result: tooltip must be hidden

**Comment by atomiks** [comment]
There's already an open PR: #91 

I will change this in the next major cuz I think it's a breaking change otherwise.

For now you can add a proxy wrapper to add this behavior, I believe..

**Comment by andrey-liventsev-ontarget** [comment]
@atomiks Thanks for quick reponse! Will wait for a release.

**Comment by atomiks** [comment]
This should be the behavior you're looking for:

```jsx
function TippyProxy(props) {
  const $this = useState({})[0];

  useLayoutEffect(() => {
    const {instance} = $this;
    if (instance.state.isVisible && !instance.state.isEnabled) {
      instance.enable();
      instance.hide();
      instance.disable();
    }
  });

  function onCreate(instance) {
     if (props.onCreate) {
       props.onCreate(instance);
     }

    $this.instance = instance;
  }

  return <Tippy {...props} onCreate={onCreate} />
}
```

**Comment by HarryvanderBeek** [comment]
I used 'disable' to keep the popup always in view. Like 'pinning' the popup. With this new behavior this does not work. Is there a way to create this same behavior?
