### ISSUE TITLE
Tippy throws a warning when used with Next.js

### ISSUE THREAD

**Issue by esausilva** [atomiks/tippy.js-react#107]
My app is being built with Next.js and when I navigate to a page that has a Tippy component I get the below warning in the console. However, I do not get the warning when I hit the page directly.

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.
    in Tippy
    in ForwardRef(TippyWrapper) (at Signup.js:147)
    in div
    in Context.Consumer
    in Context.Consumer
    in StyledComponent
    in FormElements__FormGroup (at Signup.js:145)
    in fieldset (at Signup.js:112)
    in form
    in Context.Consumer
    in Context.Consumer
    in StyledComponent
    in FormElements__Form (at Signup.js:109)
    in Mutation (at Signup.js:107)
    in Signup (at signup.js:73)
    in Fragment
    in NewUser (at signup.js:108)
    in div (at signup.js:101)
    in main
    in Context.Consumer
    in Context.Consumer
    in StyledComponent
    in signup__Main (at signup.js:100)
    in div
    in Context.Consumer
    in Context.Consumer
    in StyledComponent
    in signup__Layout (at signup.js:99)
    in SignupPage (at _app.js:118)
    in Context.Provider
    in Context.Consumer
    in ThemeProvider (at _app.js:117)
    in Context.Provider
    in ApolloProvider (at _app.js:116)
    in Container (at _app.js:113)
    in MyApp
    in RenderPromisesProvider
```

**Comment by atomiks** [comment]
Think it means `renderToString()` is being called by Next, but also `global.window` and `global.document` are defined by Next so it thinks it's a browser environment. idk what we can do, that annoying is honestly the worst and shouldn't even exist 💀

**Comment by KubaJastrz** [comment]
> `global.window` and `global.document` are defined by Next

Ugh, why? 🤔

---

Also, just quickly skimmed through [zeit/next.js](https://github.com/zeit/next.js/) repo and didn't find any occurences of `global.window` and `global.document`.

**Comment by atomiks** [comment]
Yeah it didn't happen to me when using Next when I fixed that issue in February. So it is probably some other custom config.

**Comment by esausilva** [comment]
Well, I'm not sure what it is then. I just created a clean project in CodeSanbox with Next.js and Styled Components (I'm styling Tippy with Styled Components) and I don't get the warning ¯\_(ツ)_/¯
