### ISSUE TITLE
Tippy still mounted and shows empty div when enabled changes to false

### ISSUE THREAD

**Issue by aodinok** [atomiks/tippy.js-react#109]
When enabled changes to `false` for mounted and visible Tippy it shows empty div instead of disappearing from screen.

<img width="77" alt="Screenshot 2019-07-31 at 16 15 48" src="https://user-images.githubusercontent.com/11699084/62214822-7c252000-b3ae-11e9-9d6d-1ff62d79a8e2.png">

**Comment by atomiks** [comment]
I've detailed a solution here - https://github.com/atomiks/tippy.js-react/issues/106
I am planning to change this in the next major version.
