### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by KubaJastrz** [atomiks/tippy.js-react#11]
Thank you for this amazing react wrapper :heart: 
Are you planning on adding typescript support to this package? I've seen the discussion on the main tippy repo (https://github.com/atomiks/tippyjs/issues/186).
If you need any help, I'd love to assist :slightly_smiling_face:

**Comment by martensm** [comment]
I don't have time at the moment to create a PR but would something like this be sufficient?

```typescript
import React from 'react'
import { Instance, Props } from 'tippy.js'

type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>

export interface TooltipProps extends Omit<Partial<Props>, 'content'> {
  content: JSX.Element | string
  children: JSX.Element
  onCreate?: (tip: Instance) => any
}

export default class Tooltip extends React.Component<TooltipProps> {}
```

**Comment by KateVuilova** [comment]
Hello! I've created a PR for this based on @martensm's work above. Let me know if you want any changes.
