### ISSUE TITLE
Wrapper span workaround doesn't seem to be working?

### ISSUE THREAD

**Issue by thedanchez** [atomiks/tippy.js-react#110]
First off, thank you for making an incredible library like this! Super incredible work with a clear props API and documentation!

I've been trying to use `Tippy` around a component and am experiencing difficulty getting it to work correctly.

```
 <Tippy arrow content={<PasswordRequirementsView/>}>
  <span>
    <PasswordInputField
      required
      name="password"
      data-cy="password"
      value={password}
      onChange={this.handleOnChange}
      error={{display: !!errorPassword}}
    />
  </span>
</Tippy>
```

I believe I'm using the component correctly according to what the directions provide. Below is the console error output I'm receiving.

<img width="826" alt="Screen Shot 2019-07-31 at 3 21 34 PM" src="https://user-images.githubusercontent.com/4277756/62241570-65c79600-b3a7-11e9-96f6-b95d5ae3cfe0.png">

Any ideas on what could be causing this?

**Comment by atomiks** [comment]
Old React version (<=16.7.0?)

> This error might happen if you use old React. It's not even a React error — you're calling React.useState(), and if that doesn't exist (such as in old versions), it's like calling React.lalalala(). The function doesn't exist, so you're calling undefined() and it crashes.

**Comment by thedanchez** [comment]
Ahh, thank you! Yes, that was the issue.
