### ISSUE TITLE
TypeError: React.useState is not a function

### ISSUE THREAD

**Issue by SamWorrod** [atomiks/tippy.js-react#111]
Hi there! Currently trying to implement a Tippy tooltip into a group of components, and am running into issues when doing a gradle build, where I am receiving the following error: 

<img width="938" alt="Screen Shot 2019-08-01 at 3 05 09 PM" src="https://user-images.githubusercontent.com/22182213/62320504-53fcf600-b46e-11e9-8fa6-aee347ec5b41.png">

Do you have any suggestions regarding what might have caused this?

Thanks for any help you can provide!

**Comment by JaclyneOoi** [comment]
Any chance you're not on React 18.6 or later? That's when [hooks](https://reactjs.org/docs/hooks-intro.html) were added

**Comment by SamWorrod** [comment]
Yes that's the issue, thank you!
