### ISSUE TITLE
XSS issue when passing broken html in tooltip content

### ISSUE THREAD

**Issue by saravanan10393** [atomiks/tippy.js-react#113]
When passing broken html string to content props, it shows the alert box.

`
function UserChip({ userName }) {
  return (
    <Tippy content={userName}>
      <p>{userName}</p>
    </Tippy>
  )
}
UserChip.defaultProps = {
 userName: `"><img src=x onerror="alert(1)" >`
}
`

When rendering the userChip with following content, alert box comes up

`<UserChip userName={`"><img src=x onerror="alert(1)" >`}>`

**Comment by atomiks** [comment]
`allowHTML={false}` or sanitize the string before passing it in.

**Comment by atomiks** [comment]
[Not actually experiencing this by default actually](https://codesandbox.io/s/empty-leaf-fxqsh). `createPortal()` doesn't parse `.innerHTML` so I don't know how there is an XSS vulnerability here.
