### ISSUE TITLE
Tippy Shows and Flickers Away Immediately when Click Focusing on Custom Component with Ref

### ISSUE THREAD

**Issue by thedanchez** [atomiks/tippy.js-react#114]
I have the following setup with Tippy..

```
<Tippy
  arrow
  theme="password"
  placement={tooltipPlacement}
  visible={tooltipVisible}
  distance={tooltipDistance}
  content={<PasswordRequirementsView />}
>
    <PasswordInputWithRef
      containerClassName="form-input-block"
      errorClassName="form-input-error"
      label={label}
      placeholder={placeholder}
      value={value}
      onChange={onChange}
      onFocus={onFocus}
      onBlur={onBlur}
      {...rest}
    />
  </Tippy>
```

and here is the definition of `PasswordInputWithRef`

```
const PasswordInputWithRef = React.forwardRef((props, ref) => (
  <SafeInputField
    type="password"
    innerRef={ref}
    inputRegex={regexPasswordRequirements}
    {...props}
  />
))
```

One odd thing that I'm experiencing is that when I **click** focus into the password field in my app, the tooltip appears and then immediately disappears from view. However, when I **tab** focus into the field, the tooltip appears fine. I tried playing with the `trigger` prop and setting that to "click" but that didn't work.

But it gets stranger still, and this behavior is what I'm hoping may give clues to the problem -- if I **click and hold** on the field, the tooltip remains present on the field. The moment I release the click, it goes away.

Hopefully this was clear. Any thoughts on how to resolve this?

**Comment by atomiks** [comment]
`hideOnClick={false}`

**Comment by thedanchez** [comment]
I feel like a doofus in missing that prop in the options documentation -- thank you!
