### ISSUE TITLE
Tooltip is closing if some other element was selected

### ISSUE THREAD

**Issue by JamesJGoodwin** [atomiks/tippy.js-react#115]
Hello. I have an algorithm:

1) User hovers some icon wrapped in `<Tippy />`
2) If user clicks on that icon then copy-to-clipboard function is called, where I need to render some textarea, put there some text. And then to copy this text to clipboard I need to call `select()` on that textarea to be able to execute `document.execCommand('copy')`.

The issue here is that tooltip is closing whenever some other DOM element is getting `select`ed programatically even with `hideOnClick: false` option enabled. Is it supposed to happen with React adaptation of Tippy.js? Because with regular version of tippy.js it worked just fine.

**Comment by atomiks** [comment]
CodeSandbox reproducing it will help

**Comment by JamesJGoodwin** [comment]
Well I'd be happy to but seems like CodeSandbox haven't yet dropped support for Preact X (since it's still release candidate). Tippy.js uses forwardRef which is unavailable in Preact's `preact-compat`, but available in Preact X as `preact/compat`. I tried installing Preact X but for some reason it still requires `preact-compat`.

Reproduction of my code: https://codesandbox.io/s/misty-violet-4uiue

If only you'd be able to make it work in your environment 😅 

The main concept is simple. Try to create `<Tippy />` instance and then `select()` some input or textarea on `setTimeout()` while hovering tippy reference. This should do the trick.

**Comment by atomiks** [comment]
If you can get the CodeSandbox to work for me, I can investigate, but as of now I'm not sure what to do

(this reply is extremely late because it wasn't working by default sorry 😭)
