### ISSUE TITLE
Does not work with external css <link> tag

### ISSUE THREAD

**Issue by malimccalla** [atomiks/tippy.js-react#119]
### Description 

When using an external link tag somewhere in the project the tool tip stops working.

### Steps to reproduce

1. Clone simplified reproduction repo https://github.com/malimccalla/external-link-issue
2. `yarn install`
3. `yarn run dev`
4. Hover over the button.

### Expected

Tool tip should correctly animate up and display the text "Hello"

### Actually happens

The words "Hello" just appear in the dom

### Additional info

If you remove the `<link>` tag from `pages/index.js` and refresh the page everything works as expected. The link tag can be to any external resource and doesn't necessarily need to link to css (the tag simply being `<link />` will also cause this issue)

**Comment by atomiks** [comment]
I'll check the repo tomorrow, but can I ask if this works:

```
yarn add tippy.js@4.3.4
```

(instead of 4.3.5 which I suspect you're using - gets installed as a dependency)

**Comment by malimccalla** [comment]
Thank @atomiks. Unfortunately add `tippy.js@4.3.4` didn't seem to have any affect. Here or some shots of whats happening with and without the link tag

without (expected)
![1](https://user-images.githubusercontent.com/18899991/63787834-6727a800-c8ec-11e9-99c8-796e8d4fc80a.gif)

with (the issue)
![0](https://user-images.githubusercontent.com/18899991/63787883-7ad30e80-c8ec-11e9-9bff-fb8b037f19c9.gif)

**Comment by atomiks** [comment]
Here is how the CSS is injected: https://github.com/atomiks/tippyjs/blob/master/src/css.ts

Is there something that could prevent this from working? It seems like the stylesheet isn't appearing in the `<head>` in the second example. Does the `<Head />` component mess with the `<head>` or something?

**Comment by atomiks** [comment]
FWIW, you can fix this by writing this line, assuming the whole `<head>` node is getting deleted then recreated by the `<Head />` component after tippy.js injects the CSS (so it disappears).

```js
import 'tippy.js/index.css';
```

Adds an extra kb+ cost though since the stylesheet is appearing twice in the payload (CSS file, and JS string)

**Comment by malimccalla** [comment]
Ah thanks! I believe this isnt actually an issue withTippy as I downgraded Next.js from v9 to v8 and it works as expected so must be something to do with the `Head` component as you say. Will close the issue. Thanks for you help

**Comment by malimccalla** [comment]
I have opened an issue on the Next.js repo here https://github.com/zeit/next.js/issues/8534
