### ISSUE TITLE
Tippy using inline stylesheet preventing setting a good CSP

### ISSUE THREAD

**Issue by n8ta** [atomiks/tippy.js-react#120]
My goal is to remove unsafe-inline from my script-src and style-src so all styles will be in stylesheets and all js will be in .js files.

I don't think I'm doing anything special my tippy looks like this:
```
let content = <div>
            <div className='common_name'>{this.props.common_name} </div>
            <div>(<span className='sci_name'>{this.props.sci_name}</span>)</div>
            <p>{this.props.correct} Correct / {this.props.seen} Chances</p>
        </div>;
        return (
            <Tippy content={content} placement={'bottom'}>
                <span>
                <Progressbar width={this.props.score*100} msg={(this.props.score*100).toFixed(0)+"%"}/> 
// This isn't the inline style it gets converted to a class in the sub-component
                </span>
            </Tippy>
        );
```

And I see this error in chrome:
```
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' https: unsafe-inline". Either the 'unsafe-inline' keyword, a hash ('sha256-YiTH8cN5PO9kEia4wudUAWzQ5VWkrbsqAA534fEomjM='), or a nonce ('nonce-...') is required to enable inline execution.
```

Which points to this bit of code in  index.all.js:1971
```
function injectCSS(css) {...}
```
[Full source of my project here](https://github.com/n8ta/Herpetology/blob/CSP/app/javascript/components/Speciesprogressbar.js)

There's a solution [here](https://github.com/atomiks/tippyjs/issues/338#issuecomment-434423219) but I'm not how to apply that to this package.

**Comment by atomiks** [comment]
You can create an alias for webpack to point to the CSS-less version: https://github.com/atomiks/tippy.js-react/issues/52#issuecomment-516605669

If you can't do that, you can relax the policy rules: https://stackoverflow.com/a/18428346 inline styles are not as problematic as scripts

**Comment by n8ta** [comment]
Thanks @atomiks  that did it!

To summarize for future people:
1. In config/webpack/ENV.js, you'll probably already have module.exports set so just add the key for alias if if isn't already there to and then add the key/value for tippy.js.
```
...
module.exports = environment.toWebpackConfig(); // <-- this was already there, I added the next two lines
module.exports.resolve['alias'] = {};
module.exports.resolve['alias']['tippy.js'] = 'tippy.js/esm';
```
2. Add the css in your own stylesheet. You can find the tippy default css @ [https://unpkg.com/browse/tippy.js@4.3.5/](https://unpkg.com/browse/tippy.js@4.3.5/)
