### ISSUE TITLE
Can't use within iframe

### ISSUE THREAD

**Issue by NerdCowboy** [atomiks/tippy.js-react#121]
I'm using [React Frame component](https://github.com/ryanseddon/react-frame-component ) to wrap my entire app in an iframe as I'm building a widget.

I'm getting the following errors when I try to use Tippy
`index.js:159 Uncaught TypeError: instance.set is not a function`
`index.js:148 Uncaught TypeError: instance.destroy is not a function`
`index.js:1437 The above error occurred in the <Tippy> component:
    in Tippy (created by ForwardRef(TippyWrapper))
    in ForwardRef(TippyWrapper) (at ItemDetail/index.js:84)…`

I assumed the issue was that Tippy was trying to inject itself to the document body instead of the iframe's document body, so I used React Frame's context consumer and passed its document to my component and added it to `appendTo`.

```
<FrameContextConsumer>
  {
  ({ document, window }) => {  
    return (
      <Tippy appendTo={document.body} content="Text" >
        <button>Button</button>
      </Tippy>
    )
  }}
</FrameContextConsumer>
)
```

I tried console.logging the `instance` in the `onCreate` prop and it just returned an empty array, so that'd explain why there's no methods on `instance`

Digging into Tippy's code, it appears the creation of the Tippy div is hardcoded to the main document

```
export function ssrSafeCreateDiv() {
  return isBrowser && document.createElement('div')
}
```

Is there something I'm missing to allow usage within an iframe? Or am I correct that `ssrSafeCreateDiv` would need to be refactored to allow passing in a different document?

**Comment by Slapbox** [comment]
I'm seeing this randomly in an Electron environment, but pretty frequently. I recently updated from `2.2.0` to `2.2.3`.

Can we change the title to reflect that the issue affects more than just iframes.

**Comment by atomiks** [comment]
> I tried console.logging the instance in the onCreate prop and it just returned an empty array, so that'd explain why there's no methods on instance

Means an invalid `targets` argument (the button ref was not defined) was being passed to `tippy()` core which seems odd

**Comment by atomiks** [comment]
Found the issue in tippy core:

`value instanceof Element` (`value` === `<button>` node) this is returning false.

So somehow the button node within the frame's context is not an instanceof `Element`

**Comment by atomiks** [comment]
Run:

```bash
npm i @tippy.js/react@latest
```

iframes should be supported now

**Comment by NerdCowboy** [comment]
Awesome! 🎉 Got temporarily pulled onto a different project, but I'll try to check it out sometime this week. Thanks @atomiks!
