### ISSUE TITLE
Render content component only when tooltip is visible

### ISSUE THREAD

**Issue by gabrielfnogueira** [atomiks/tippy.js-react#122]
Hey there! I started migrating from `react-tippy` since it seems it's no longer maintained (and I needed the `appendTo` prop 😁 ). One of the features I'm missing is that `react-tippy` used to render the content Component only when the tooltip is triggered by default.

This was useful because we have some side-effects and some computation in the content Component. Using `tippy.js-react`, the content Component is always rendered "on page load", so all our side-effects and computation run immediately. And having one tooltip in each row on a 100+ items list makes our application unresponsive/really slow for a little while 😅 

I've tried a couple different approaches but I couldn't make it work. Maybe I'm missing something 🤔 

Is there a way to accomplish this in the current release? Can you point me in the right direction?

**Comment by gabrielfnogueira** [comment]
The closest I've gotten is this:

```javascript
const MyTooltip = () => {
    const [shouldRender, setShouldRender] = useState(false);

    return (
        <Tippy
            interactive
            placement="right"
            theme="light"
            arrow
            appendTo="parent"
            onShown={() => setShouldRender(true)}
            content={
                shouldRender ? (
                    <MyComponent />
                ) : (
                    <Loader />
                )
            }
        >
            <i className="fa fa-info-circle tooltip-icon" />
        </Tippy>
    );
};
```

Since I'm already rendering `<Loader />` inside `MyComponent` while the calculation isn't finished, it seems unnoticeable 😎

**Comment by atomiks** [comment]
I was just writing a big comment when your comment popped up - that's basically how I was doing it! Depends if you want `onShow` (before it starts transitioning in) or `onShown` as you have (once the transition finishes)

**Comment by gabrielfnogueira** [comment]
I guess I just needed a coffee break to figure it out. Thanks @atomiks for your time and for this awesome library!
