### ISSUE TITLE
Tooltip not showing when wrapping disabled button

### ISSUE THREAD

**Issue by Slapbox** [atomiks/tippy.js-react#123]
I wasn't seeing this issue in `2.2.0` but am now in `2.2.3` - I haven't rolled back to test `2.2.0` again specifically for this issue, but I'm able to provoke the issue by programmatically adding `disabled` to the DOM from my code, or by manually add `disabled` to an element.

I'm not sure how this is able to affect Tippy? Seems very weird.

I'm seeing no tooltip when using this code:

```js
    <Tippy content={title}>
      <button disabled {...{ ...props, title: '' }}>{buttonText}</button>
    </Tippy>
```

But it works fine without `disabled`
```js
    <Tippy content={title}>
      <button {...{ ...props, title: '' }}>{buttonText}</button>
    </Tippy>
```

**Comment by atomiks** [comment]
This isn't possible because some browsers don't fire events on disabled elements - Tippy normalized it so it never works. If you're setting disabled, use a wrapper `<span>` instead, like

```jsx
<Tippy content={title}>
  {disabled ? <span><button disabled /><span> : <button />}
</Tippy>
```

**Comment by Slapbox** [comment]
Works beautifully! Thank you!
