### ISSUE TITLE
[v3.0.0] Default option for appendTo is not document.body

### ISSUE THREAD

**Issue by JamesJGoodwin** [atomiks/tippy.js-react#125]
Hello. I have updated to the latest version and expiriencing some issues with it. 

1) By default `<Tippy />` is now appending itself to `reference` parent while documentation says that default options is `document.body`. I need to set it explicitly in order to make it work.

2) Option `interactive` is getting ignored while `appendTo` is not `document.body`. `hideOnClick={false}` can fix that but console will be showing this warning:

![image](https://user-images.githubusercontent.com/17240507/65905632-950b7b00-e3c9-11e9-958a-542fe16e4c4d.png)

Is this an expected behavior?

**Comment by atomiks** [comment]
1. Documentation needs to be updated for this yeah.

 If `interactive: true`, then the tippy is appended to the reference element's parent node unless you specify your own `appendTo` value – that way, interactive elements inside the tippy can be focused next once the reference element is blurred. 

If it's appended to the body (as before), then any focusable elements in between the ref element and the end of the body will be next in focus order, so the popover is "disjoined" for keyboard use making it inaccessible. 

You can disable this default behavior if you use your own `appendTo`, but you would need to create some kind of focus management solution to handle the popover for keyboard.

2. Not 100% sure what you mean here, is there a CodeSandbox repro?

**Comment by JamesJGoodwin** [comment]
>Not 100% sure what you mean here

`interactive: true` has no effect while `appendTo` is not set to `document.body`

**Comment by atomiks** [comment]
Works for me: https://codesandbox.io/s/pensive-villani-mdzcv

**Comment by JamesJGoodwin** [comment]
@atomiks well then I think there's something wrong with my code. I'll try to inspect it and reopen this issue if there's a bug.

**Comment by wahlstedt** [comment]
This should be in the upgrade guide. One of my popups stopped showing after upgrading to v3, and I finally found out that it was because it had `interactive: true`

It started showing up again after adding `appendTo: document.body`

**Comment by atomiks** [comment]
How was it invisible, due to overflow hidden? How are you handling keyboard nav?

**Comment by wahlstedt** [comment]
I think it happens because the popper in question has `preventOverflow: { enabled: false }`

As for keyboard navigation, I simply ignore that. 8)
