### ISSUE TITLE
TippySingleton example not working in TypeScript

### ISSUE THREAD

**Issue by JamesJGoodwin** [atomiks/tippy.js-react#126]
Hello. [TippySingleton example](https://github.com/atomiks/tippy.js-react#-tippysingleton-) is not working in TypeScript environment and erroring in this:

>Type '{ children: Element[]; }' is missing the following properties from type 'TippySingletonProps': allowHTML, animation, appendTo, aria, and 40 more.ts(2740)

Here's my CodeSandbox: https://codesandbox.io/s/exciting-murdock-s8rhi

**Comment by atomiks** [comment]
Can you take a look here?: https://github.com/atomiks/tippy.js-react/blob/5aea6bdcf92842a2dd2586fc4c3592f831198d27/index.d.ts

I'm not the best with these type thingies. 

cc @KubaJastrz

**Comment by KubaJastrz** [comment]
It was using `Options` before which is now `Partial<Props>` and not `Props`.

We should change it here as well.

**Comment by atomiks** [comment]
> It was using Options before which is now Partial<Props> and not Props.

That makes sense.

Would also be good to convert the src over to TS, since there's not much code in this wrapper, it shouldn't take too long – would catch this type of thing?

**Comment by KubaJastrz** [comment]
Probably, we could also add tests for typings, like you can see [here](https://github.com/chalk/chalk/blob/eef8c8c191d25deecde8c472e10a37c6f736e2e9/index.test-d.ts) for example.

**Comment by atomiks** [comment]
`3.0.1`
