### ISSUE TITLE
Interactive tippy element may not be accessible via keyboardnavigation.

### ISSUE THREAD

**Issue by ReTWi** [atomiks/tippy.js-react#131]
If tippy placed one after another i get this error:
`Interactive tippy element may not be accessible via keyboardnavigation.Ensure the tippy element is directly after the reference(or triggerTarget) element in the DOM source order. Using a wrapper<div> or <span> element around it can solve this.`

Example with problem:
```
<Tooltip content='tipx'>
        <span>x</span>
</Tooltip>
<Tooltip content='tipy'>
        <span>y</span>
</Tooltip>
```

Example without problem:
```
<div>
   <Tooltip content='tipx'>
      <span>x</span>
  </Tooltip>
</div>
<Tooltip content='tipy'>
     <span>y</span>
</Tooltip>
```
```
function Tooltip({ children, content, ...rest }) {
  if (!children) return null
  if (!content) return children

  return (
    <Tippy content={content} {...rest}>
      {children}
    </Tippy>
  )
}
```
Everything was fine before i updated to 5+ version

**Comment by atomiks** [comment]
What's the problem exactly? The warning is working as it should

**Comment by ReTWi** [comment]
@atomiks emm, how can i fix this and don't get warning?

**Comment by atomiks** [comment]
Yes wrapping in a parent node is the easiest fix (only needs to be done for interactive ones).

> If it's only keybord navigation problem, then how can i stop this wargning from showing?

`appendTo={document.body}` if you're using a focus management solution instead. You can't just ignore keyboard navigation though :\
