### ISSUE TITLE
Creating a singleton with <Tippy> instances that aren't adjacent to eachother

### ISSUE THREAD

**Issue by inxilpro** [atomiks/tippy.js-react#132]
I have 5 tippy instances in a container, but there are a few other items in the container between some of them. Essentially:

```jsx
<div>
  <Tippy />
  <Tippy />
  <button />
  <Tippy />
  <button />
  <Tippy />
  <Tippy />
</div>
```

Is there a way to convert all the `<Tippy>` instances into a Singleton using the existing API? As far as I can tell, `<TippySingleton>` expects all its children to be tippy instances.

I'm pretty sure I can figure out my own solution, but I'm just wondering if there's an official way to implement this strategy.

**Comment by inxilpro** [comment]
Two solutions that I've tinkered with in my head are either a `useSingleton()` hook that would behave something like:

```jsx
const singleton = useSingleton();

return (
  <div>
    <Tippy singleton={singleton} />
    <button>
    <Tippy singleton={singleton} />
  </div>
);
```

Or else `<TippySingleton>` could utilize the Context API such that each tippy instance checks for a parent singleton context and either creates a new tippy instance or "joins" the parent singleton context…

**Comment by atomiks** [comment]
I think we could filter out the non-`<Tippy />` children?

**Comment by inxilpro** [comment]
I’ve implemented the hook option locally and it seems to work pretty well. The API is pretty much the same as my original comment. You call a `useSingleton` hook that sets up all the refs and effects that `TippySingleton` uses, and then passing that to the `Tippy` instance sets up the `onCreate` callback and forces the instance into a disabled state. I’ll submit a PR in a bit…
