### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by mikearche** [atomiks/tippy.js-react#134]
TippyProps is currently missing the appropriate types to be able to use this library with typescript.

**Comment by atomiks** [comment]
Whats missing?

**Comment by atomiks** [comment]
I'm noticing that props autocomplete is not working + passing invalid types like `delay={true}` is not erroring.

I think the culprit is the `[key: string]: any` that allows you to pass anything in (for plugins), but it should probably be removed and force the user to create strict types?

```ts
interface Props extends LifecycleHooks {
  // ...
  [key: string]: any;
}
```

**Comment by mikearche** [comment]
Apologies for not responding to this sooner. I should have put more detail into what was actually wrong.

This seemed to fix the issue. Thanks for responding so quickly.
