### ISSUE TITLE
Singleton limitations: overriding placement, className on a per-tooltip basis

### ISSUE THREAD

**Issue by Silverwolf90** [atomiks/tippy.js-react#153]
I'm unsure if this is a limitation of tippy.js or this react wrapper. 

What I'm looking to do is share a delay across all tooltips on a page (ie: global delay), but on a per-tooltip basis I might want different placement (or style).

Is this possible to do? Based on my limited experiments with the `useSingleton` hook, I was unable to override `placement` (or `className`) on a per-tooltip basis when simultaneously using the `singleton` prop. 

(On a related note, it doesn't look like the `plugins` prop works with `singleton` prop. I was only able to get it working without the `singleton` prop.)

Using:
* Chrome 78
* `@tippy.js/react@3.1.1`
* `react@16.10.2`

**Comment by atomiks** [comment]
`useSingleton` accepts its own props and only uses `content` from child `<Tippy />`s. I guess we could check if `<Tippy />` prop matches `tippy.defaultProps` (to see if the prop was user-defined), and if not, then we override the singleton's own prop. That should allow the behavior you're looking for. Probably needs to be implemented in core.

> (On a related note, it doesn't look like the plugins prop works with singleton prop. I was only able to get it working without the singleton prop.)

Would be nice to get a repro for this!

**Comment by atomiks** [comment]
Found a way to achieve this without any feature additions or changes  (hopefully, there may be unconsidered edge cases)

**(Note: `popperInstance`-related props like `placement` are buggy due to core, there is a quick fix I need to make in core for this to work properly).**

In React the usage is like:

```jsx
// Make a hash of all the props you want to accept to override the singleton's
const individualProps = {
  placement: true,
};

function App() {
  const tippyInstancesRef = useRef([]);
  const singleton = useSingleton({
    onTrigger(instance, event) {
      const tippyInstance = tippyInstancesRef.current.find(
        i => i.reference === event.currentTarget,
      );
      instance.setProps(
        Object.entries(tippyInstance.props).reduce((acc, [key, value]) => {
          if (individualProps[key]) {
            acc[key] = value;
          }
          return acc;
        }, {}),
      );
    },
  });

  function onCreate(instance) {
    tippyInstancesRef.current.push(instance);
  }

  return (
    <>
      <Tippy
        content="x"
        placement="right"
        singleton={singleton}
        onCreate={onCreate}
      >
        <button />
      </Tippy>
      <Tippy
        content="y"
        placement="bottom"
        singleton={singleton}
        onCreate={onCreate}
      >
        <button />
      </Tippy>
    </>
  );
}
```

I am assuming this could be abstracted to allow for "global shared timers" everywhere.

**Comment by Silverwolf90** [comment]
Wow thank you for the very prompt response-- this seems to work great for placement!

Unfortunately it doesn't work for `className` though. I was glancing through the internals and it looks like that's handled entirely in the react wrapper and tippy.js doesn't have a corresponding prop (...if my understanding is correct).

**Comment by atomiks** [comment]
Ugh yeah I realized that as well. You can manually add it to `instance.popperChildren.tooltip` though, with an abstraction it should be neat to use

**Comment by Silverwolf90** [comment]
I think I've got a version of this working. But I'm not sure if this is what you meant...

I'm now adding the classes manually to `instance.popperChildren.tooltip` in the `onShow` lifecycle hook. I also had to add `onShow` to the `invidivualProps` object from the code you posted above:

```js
const individualProps = {
  placement: true,
  onShow: true,
};
```

And my tooltip object now looks like this

```js
const TooltipBase: React.FC<TippyProps> = ({
  content,
  placement = 'top',
  className = '',
  children,
  ...props
}) => {
  // Hook that uses the code you posted above
  const { singleton, onCreate } = useTippy();

  const onShow = React.useCallback(
    (instance) => {
      className.split(' ').forEach(className =>
        instance.popperChildren.tooltip.classList.add(className)
      );
    },
    [className]
  );

  return (
    <Tippy
      content={content}
      singleton={singleton}
      onCreate={onCreate}
      onShow={onShow}
      placement={placement}
      {...props}
    >
      {children}
    </Tippy>
  );
};

export const Tooltip = styled(TooltipBase)`
  ...
`;
```

Does this make sense? Or is there a better way you had in mind?

**Comment by atomiks** [comment]
That's the general idea yeah.

I think the `className` should be added in `useLayoutEffect`, you could store the instance in a ref to do that.

Also, you need to be returning a cleanup function using `classList.remove()` to remove stale classes when `className` dep changes.

**Comment by Silverwolf90** [comment]
👍 thanks a lot for your help! Much appreciated 🙏

**Comment by Silverwolf90** [comment]
Sorry to reopen this, but I've been banging my head against the wall and can't seem to get this working.

While I've been able to apply the classNames on first interaction with `useLayoutEffect`, I haven't been able to figure out how to handle changing the classes. [I've put together a code sandbox](https://codesandbox.io/s/black-frog-xvbxs) where you'll see that styles do not change correctly.

I came to realize that `onShow`/`onHidden` is only called for the first/last tooltip within the delay time, so maybe I should be using `onBeforeUpdate` to handle the tooltip changes? But I couldn't put together a mechanism that seemed to handle that.

Any advice is much appreciated.

**Comment by atomiks** [comment]
The `className` needs to be added to the singleton tippy DOM node. In your example, it's being applied to the individual tippy (where nothing happens).

**Comment by atomiks** [comment]
https://codesandbox.io/s/little-fire-lohti

Easy way is just to set `.className` actually by reading the `tippyInstance` className 🤷‍♂

**Comment by Silverwolf90** [comment]
Aha! That makes total sense now. Thanks!
