### ISSUE TITLE
Error Jest Test with react-test-renderer

### ISSUE THREAD

**Issue by soyandresdev** [atomiks/tippy.js-react#158]
I have a component with Tippy. But a test with `react-test-renderer`,  I get error  like that:
` Error: Uncaught [Error: tippy() was passed `null` as its targets (first) argument.

      Valid types are: String, Element, Element[], or NodeList.]`

`<Tippy content={item.text}>
                    <span>
                      {item.badge && <Badge>{item.number}</Badge>}
                      <Icons
                        type={item.icon}
                        width="30"
                        height="30"
                        fill="currentColor"
                      />
                    </span>
                  </Tippy>`

`
  ● Test component [App] › Renders correctly defaultProps [App]

    tippy() was passed `null` as its targets (first) argument.

    Valid types are: String, Element, Element[], or NodeList.

       5 | describe("Test component [App]", () => {
       6 |   it("Renders correctly defaultProps [App]", () => {
    >  7 |     const rendered = renderer.create(<App />);
         |                               ^
       8 |     // expect(rendered.toJSON()).toMatchSnapshot();
       9 |   });
      10 | });`

**Comment by atomiks** [comment]
Debugging tips:

[`component.ref` is `null`](https://github.com/atomiks/tippy.js-react/blob/495a70b9d80e56077fbbe23a14e735a9c8293573/src/Tippy.js#L56) when passed to `tippy()`.

[Here is where it's assigned directly](https://github.com/atomiks/tippy.js-react/blob/495a70b9d80e56077fbbe23a14e735a9c8293573/src/Tippy.js#L112)

[Here is the `ref` preservation in `forwardRef`](https://github.com/atomiks/tippy.js-react/blob/495a70b9d80e56077fbbe23a14e735a9c8293573/src/Tippy.js#L143)

Try logging in `node_modules` to see what's happening
