### ISSUE TITLE
Closing interactive Tippy when link clicked inside

### ISSUE THREAD

**Issue by sebastianschrama** [atomiks/tippy.js-react#16]
First of all thanks for the great plugin!

I have a tippy tooltip with some links inside. How can I close the tippy when I clicked links inside?

Thanks in advance!

Kind regards
Sebastian

**Comment by atomiks** [comment]
You can add `onClick` handlers to the links that call the `hide()` method on the tippy instance. Store the instance in the component using the `onCreate` callback prop.

```jsx
class Tip extends Component {
  onCreate = tippy => {
    this.tippy = tippy
  }

  closeTippy = () => {
    this.tippy.hide()
  }

  render() {
    return (
      <Tippy
        onCreate={this.onCreate}
        content={
          <a onClick={this.closeTippy} href="#">
            Link
          </a>
        }
        interactive={true}
      >
        <button>Button</button>
      </Tippy>
    )
  }
}
```

**Comment by sebastianschrama** [comment]
Thanks for the quick answer. This is working like a charm!
