### ISSUE TITLE
Importing CSS modules - Webpack sideEffects

### ISSUE THREAD

**Issue by josh-meredith** [atomiks/tippy.js-react#161]
Hi there,

I've noticed when importing the tippy.js CSS module into my Gatsby site, it gets stripped out during the build process. After looking into it further it seems to be due to Webpack tree-shaking, as CSS doesn't usually provide an export.

The author of Webpack recommends to exclude CSS files from this process like [this](https://github.com/webpack/webpack/issues/6741#issuecomment-372720641).

You can also see another example of a similar problem occurring [here](https://github.com/gatsbyjs/gatsby/issues/19446).

Would you mind if I submit a PR to make this change?

Thanks!

**Comment by atomiks** [comment]
[This is already marked in `tippy.js`](https://github.com/atomiks/tippyjs/blob/master/package.json#L9-L12) - maybe the glob pattern is wrong?

**Comment by atomiks** [comment]
@josh-meredith are you able to edit tippy.js' package.json with just `"*.css"` instead of the current pattern and see if that fixes it? Or is it required for `@tippy.js/react`?

**Comment by atomiks** [comment]
We had weird issues with Gatsby CSS for the production version while working on the Popper 2 docs. The bug seems really bad but they haven't solved it yet — my guess is that's what this is. `micromatch` reports the CSS files to match correctly which is what webpack uses.
