### ISSUE TITLE
onShown not firing

### ISSUE THREAD

**Issue by guidupuy** [atomiks/tippy.js-react#162]
Hey, I'm now using the latest version of the package and my `onShown` lifecyle hooks have all stopped firing. Is this expected?

**Comment by atomiks** [comment]
Animations were removed from core (except `fade`) so you need to import them back if you were using a different animation. If `duration` is not `0`, and the CSS transitions aren't enabled, it won't be called.

**Comment by guidupuy** [comment]
I'm using `fade` with a non-zero `duration`. I'd like to `focus` a `ref`'ed field in the tippy after the tippy is shown. Doing that in `onShow` doesn't work. How would you do it with the current version?

**Comment by guidupuy** [comment]
Also, the tippy's `onShown` attribute is set to `false` probably as a result of `onShown` not being called. Is `isVisible` the right attribute to use instead then?

**Comment by atomiks** [comment]
`state.isVisible` is `true` onShow and `false` onHide, whereas `state.isShown` is `true` onShown and `false` onHide

The `ontransitionend` listener listens for `visibility` transition changes only in 5.1.3 – it's possible this has caused a problem somewhere. Is it called in 5.1.2?

**Comment by atomiks** [comment]
^ It was a bug! Sadly the Jest tests didn't pick up the regression :\

Should be fixed if you update to latest `@tippy.js/react@latest`.

**Comment by guidupuy** [comment]
Thanks!
