### ISSUE TITLE
setContent is not working

### ISSUE THREAD

**Issue by sebastianschrama** [atomiks/tippy.js-react#17]
Hi,

I want to use dynamic content for a tippy. Unfortunately I'm not able to change the content.

This is my component:
```
import React, { Component } from 'react'
import Tooltip from '@tippy.js/react'

export class ContextMenu extends Component {
	onCreate = tippy => {
		this.tippy = tippy
	}

	closeTippy = () => {
		this.tippy.hide()
	}

	renderInitialContent = () => (
        <button onClick={this.showConfirmation}>
            Delete
        </button>
	)

	renderConfirmationContent = () => (
        <button onClick={() => { this.closeTippy(); this.props.onRemove() }}>
            DELETE!
        </button>
	)

	showInitialContent = () => {
		this.tippy.setContent(this.renderInitialContent())
	}

	showConfirmation = () => {
		this.tippy.setContent(this.renderConfirmationContent())
	}

	render() {
		return (
			<Tooltip
				onCreate={this.onCreate}
				trigger="click"
				interactive
				content={this.renderInitialContent()}
			>
				<button>
					Show modal
				</button>
			</Tooltip>
		)
	}
}

export default ContextMenu

```

I have no errors in the console, but clicking on the "Delete"-Button doesn't switch the content to show the confirmation button "DELETE!".

What is my failure here?

Thanks in advance and kind regards
Sebastian

**Comment by atomiks** [comment]
You're forgot the `return` keyword inside the `renderInitialX()` methods. Also try using the `content` prop in the `render()` method instead of using `setContent` imperatively.

However that makes me think there needs to be a declarative way (using a prop) to manually show the tippy as well rather than imperatively calling `.show()` and `.hide()` on the instance.

**Comment by sebastianschrama** [comment]
Thanks for your reply. The setContent is working now, there was another mistake I made in the parent component.

Nevertheless I'm not yet able to adapt the whole thing to my needs.

1. Can I pass a JSX Node with setContent? This is not working, I think. Instead of the content I just see [object, object]...
2. When I now click the button within the Tippy to switch the content, the content switches, but the tippy closes. Why is this the case even though I have set interactive to true?

Thank you very much for your help!

**Comment by atomiks** [comment]
@sebastianschrama See the edit I made, you should use the `content` prop instead of `.setContent()`

2. isn't happening for me here: https://codesandbox.io/s/2owo3j80mr

**Comment by sebastianschrama** [comment]
@atomiks Thank you very much. We really appreciate your help! Meanwhile we figured out, that this is definitely no problem with Tippy but with one of our components in which we use Tippy.

By the way: You should provide a link to your personal Amazon wish list or a donation button. ;-)
