### ISSUE TITLE
Is there a way to use css selectors like with tippy.js?

### ISSUE THREAD

**Issue by jonthemango** [atomiks/tippy.js-react#170]
I am looking to use the `content` prop from the <Tippy> component and pass in my own component into this prop but also be able to decide which DOM element I want it to wrap.

When using the `<Tippy>` component, I cannot use css selectors to wrap `<Tippy>` around a given DOMElement like in tippy.js. When using just tippy.js I can use the css selector feature but I cannot pass components to be rendered by the popper, only HTML strings.

I have contemplated/attempted:
-  Potentially using `ReactDOM.createPortal(child, container)` to try and forcefully wrap `<Tippy>` around a given DOMelement. 
- Using `renderToString(component)` from `ReactDOM/server` to render components, however the HTML string loses all JavaScript / react statefulness.

Neither of these libraries seem to be able to do both features offered by tippy.js and this react wrapper. Is there a way to do both with either of the two libraries? 

Ideally looking for something like this
```JavaScript
<Tippy content={<MyComponent/>} interactive={true}>
        {children} {/* where children is an element in the dom */}
</Tippy>
```

Thanks in advance! #39 seems related but I'm not 100% sure.

**Comment by atomiks** [comment]
There isn't since I don't think it works well with React, but `@tippy.js/react` exports `tippy` so you can use it for these types of cases, just ensure you're handling the lifecycle (`.destroy()`, etc) correctly 😃

**Comment by jonthemango** [comment]
Thanks @atomiks! 

I'm going to leave this here as I was able to do this using just `tippy.js` and  `ReactDOM.createPortal` after looking through the source of this library for inspiration. 

```javaScript
import React, { useState, useContext, useEffect } from "react"
import tippy from 'tippy.js';
import {createPortal} from 'react-dom';

function ContentComponent(props){
    return <>
          <button onClick={_ => alert(1)}>Button</button>
    </>
}

const selector = "#123"

export default function Main(props) {
     const [tooltip, setTooltip] = useState(null)
     useEffect(()=> {
           let div = document.createElement("div")
           let instance = tippy(selector, {content:div})
           setTooltip(instance[0])
     }, []) // on load

     return <>
           {tooltip && createPortal(<ContentComponent/>, tooltip.popperChildren.content)}
     </>
}
```
This essentially allows you to 
1. Define a selector using tippy
2. Render react components inside tippy tooltips

Obviously there's probably more lifecycle methods that need to be implemented here.

![image](https://user-images.githubusercontent.com/10063663/75072530-a7479c00-54c5-11ea-90e3-d0cb5557999e.png)
