### ISSUE TITLE
Changing the arrow placement on a tooltip

### ISSUE THREAD

**Issue by ryanjmack** [atomiks/tippy.js-react#171]
I've been working on implementing a tooltip in a project, and we were wondering how to modify the position of the arrow in relation to the tooltip.

Standard arrow placement:
![Screen Shot 2020-02-19 at 11 18 01 AM](https://user-images.githubusercontent.com/17010097/74867441-876b7900-5309-11ea-85cb-8936104fd23d.png)

Preferred arrow placement:
![Screen Shot 2020-02-19 at 11 17 50 AM](https://user-images.githubusercontent.com/17010097/74867468-92260e00-5309-11ea-8fad-e169689a0d85.png)

So I did a lot of research, and it seemed to me that a feasible solution was to pass a prop `popperOptions` with a modifier for the arrow, but according to the [popper documentation](https://popper.js.org/docs/v2/modifiers/arrow/#padding), it seems this feature is only available in v2?

I know for sure, that a way to fix this issue would be to use CSS, but since the placement of the arrow is set using inline styles, you'd have to use `!important`, which we'd like to avoid if possible.  I was just wondering if there were any other potential solutions that I might be overlooking?

Thanks!

**Comment by atomiks** [comment]
It's the `margin` on the arrow I think. You can override them.

**Comment by ryanjmack** [comment]
Thanks, makes sense. I was fixated on the `left` attribute.
