### ISSUE TITLE
Install the package

### ISSUE THREAD

**Issue by vbtux** [atomiks/tippy.js-react#172]
Hi, I wanna install this package by run this command:
npm i @tippy.js/react 

but I get the following error,How can I fix it?

At line:1 char:7
+ npm i @tippy.js/react
+       ~~~~~~
The splatting operator '@' cannot be used to reference variables in an expression. '@tippy' can be used only as an 
argument to a command. To reference variables in an expression use '$tippy'.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : SplattingNotPermitted

**Comment by KubaJastrz** [comment]
Check readme for installation.

**Comment by atomiks** [comment]
I created a new org a couple weeks ago without the dot (`@tippyjs`) which causes the issue on Windows, I am going to put the next major there.
