### ISSUE TITLE
Custom Position Tooltip Without React Child Doesn't work

### ISSUE THREAD

**Issue by ALITHEALI** [atomiks/tippy.js-react#173]
Hi!

**Problem:** 
(Disclaimer: This issue is probably my mistake) but I've been using Popper previously for modals and was thinking of having Popper's [Usage without a reference HTMLElement](https://github.com/popperjs/react-popper#usage-without-a-reference-htmlelement) with Tippy that I came across [Custom position section of the Tippy docs](https://atomiks.github.io/tippyjs/misc/#custom-position) and I tried it with Tippy.js-React like this: 
```ts
<Tippy
      content="Hello"
      onCreate={instance => {
        if (instance.popperInstance) {
          instance.popperInstance!.reference = {
            clientHeight: dimensions.height,
            clientWidth: dimensions.width,
            getBoundingClientRect: () => {
              return {
                left: rect.left,
                right: rect.right,
                top: rect.top,
                bottom: rect.bottom,
                height: rect.height,
                width: rect.width
              };
            }
          };
        }
      }}
    >
      <button>Hello</button>
    </Tippy>
```
It shows up but it is not in its position and it already has a child which is the `<button></button>`, probably I was expecting something like this:

```ts
    <Tippy
      content="Hello"
      onCreate={instance => {
        if (instance.popperInstance) {
          instance.popperInstance!.reference = {
            clientHeight: dimensions.height,
            clientWidth: dimensions.width,
            getBoundingClientRect: () => {
              return {
                left: rect.left,
                right: rect.right,
                top: rect.top,
                bottom: rect.bottom,
                height: rect.height,
                width: rect.width
              };
            }
          };
        }
      }}
    />
```
But Both Typescript and React don't like it because they both expect the child in the TIppy Element.

**Ways to reproduce:** 
Mentioned in the problem section.

**Issue**
Is there any way I can have Tippy without a React child and be positioned with costum position?

Thanks a lot in advance. 

*Edit: A word.*

**Comment by atomiks** [comment]
This is not something I've explored with this component yet. You can fallback to the core `tippy()` constructor for now.

Maybe a Hook is needed for this functionality?

**Comment by ALITHEALI** [comment]
Hello! Thanks for getting back to me. Yes, I just tried it with `lazy={false}`, it showed up in the right place but it only shows up when I hover above the `<button></button>` child. 
Yes, indeed, a Hook is a fantastic pathway that can solve this issue with ease but as you said I fallback to the core tippy() for the time being but please let me know if I can help with anything, this is a fantastic library and thanks a lot for offering it to the community. 🙏🏻

**Comment by atomiks** [comment]
This should work fine in `@tippyjs/react` v4.0.0-alpha.1 (no dot, it's a new package entirely), since it doesn't require a child and you can use the `getReferenceClientRect` prop 😃

**Comment by ALITHEALI** [comment]
This is amazing! Thanks a lot! I'm using it in prod already. ❤️

**Comment by ilyabo** [comment]
Unfortunately, this approach doesn't seem to work in 4.2.0 anymore.  At least I couldn't get it to work. When trying to pass `lazy={false}` I get an error that it is not a valid prop. So when `onCreate` is called `popperInstance` is null. Also, `reference` is moved to `state.element` in `popperInstance`, so the full path is `instance.popperInstance.state.elements.reference`.

**Comment by ilyabo** [comment]
Ah, sorry, found `getReferenceClientRect` now. This works great!
