### ISSUE TITLE
Install the package

### ISSUE THREAD

**Issue by nikelborm** [atomiks/tippy.js-react#174]
![Screenshot_1](https://user-images.githubusercontent.com/29357907/75633637-ba6e1080-5c17-11ea-81c8-af99daaf2777.png)

**Comment by nikelborm** [comment]
After many attempts to change the installation command
![Screenshot_2](https://user-images.githubusercontent.com/29357907/75633722-792a3080-5c18-11ea-9aad-e88f251f8eb3.png)

**Comment by nikelborm** [comment]
Having previous files I get an error
![Screenshot_3](https://user-images.githubusercontent.com/29357907/75633776-08374880-5c19-11ea-855b-f050e43f4220.png)

**Comment by nikelborm** [comment]
my package.json
![Screenshot_4](https://user-images.githubusercontent.com/29357907/75633836-a62b1300-5c19-11ea-8fbc-3cbc561042b5.png)

**Comment by nikelborm** [comment]
I did not change this file myself, it became so after unsuccessful installation attempts

**Comment by KubaJastrz** [comment]
Just change the line to `"@tippy.js/react": "^3.1.1",` and run `npm install`. It should work 🤔

**Comment by nikelborm** [comment]
I tried changing the version and then ran the command npm i
![Screenshot_5](https://user-images.githubusercontent.com/29357907/75633927-4d0faf00-5c1a-11ea-8588-2b1b43cf41d2.png)
