### ISSUE TITLE
Importing Tippy 1.0.0-beta.1

### ISSUE THREAD

**Issue by elya158** [atomiks/tippy.js-react#2]
After adding `import Tippy from '@tippy.js/react'` to my code, in the browser the Tippy.js source code looks like this:
```
    // NOTE: DOM access here
    // restores the original style properties after the offsets have been com"use strict";
puted
    popperStyles.top = top;
    popperStyles.left = left;
    popperStyles[transformProp] = transform;
```

Looks like the comment is interrupting the code flow. "puted" is added to a new line. Can you look into this?

**Comment by atomiks** [comment]
Can't see that issue here:

![img](https://i.gyazo.com/4b37d22f696e1cd6cd1e311551387f44.png)

In the next version I'm not going to bundle Tippy with the component, it will be an external dependency. Not sure if that will fix it though.

**Comment by atomiks** [comment]
Assuming this isn't an issue in the latest version?
