### ISSUE TITLE
preventOverflow

### ISSUE THREAD

**Issue by Ciberusps** [atomiks/tippy.js-react#22]
How to use https://atomiks.github.io/tippyjs/#all-options-tooltips-inside-a-scrollable-container
Do u want to add some api for tippy functions? 
Or u can change exports on?
```
export default Tippy
export { tippy }
```

**Comment by atomiks** [comment]
Pass an object to `popperOptions`?

```jsx
<Tippy
  popperOptions={{
    modifiers: {...}
  }}
>
  <button />
</Tippy>
```
