### ISSUE TITLE
Failed prop type: Invalid prop `content` supplied to `Tippy`.

### ISSUE THREAD

**Issue by BofEmptiness** [atomiks/tippy.js-react#28]
For some reason i've get a  "Warning: Failed prop type: Invalid prop `content` supplied to `Tippy`." with this code

```
export default function Home() {
  const [somevar, setSomevar] = useState(1) //new react api
  return (
      <Tippy content={somevar}>
        <button>My button</button>
      </Tippy>
  )
}
```

Is there some problem with new api?

**Comment by atomiks** [comment]
I used the new Hooks API just fine with Tippy [here](https://github.com/atomiks/rate-my-life).

What type is `one`?

**Comment by BofEmptiness** [comment]
It's number one, renamed in code.

**Comment by atomiks** [comment]
`content` needs to be a `String` or `ReactElement`

Pass it to `String`

```js
export default function Home() {
  const [somevar, setSomevar] = useState(1) //new react api
  return (
      <Tippy content={String(somevar)}>
        <button>My button</button>
      </Tippy>
  )
}
```

**Comment by BofEmptiness** [comment]
Oh, soorry, didn't see it in docs. Thanks.
