### ISSUE TITLE
compatibility with CSS-in-JS libraries

### ISSUE THREAD

**Issue by cusxio** [atomiks/tippy.js-react#3]
Currently, the following line of code will not work if the user is using libraries such as [styled-components](https://github.com/styled-components/styled-components), because `ref` will be pointing towards the `styled-components` instance.

https://github.com/atomiks/tippy.js-react/blob/39eaf15aa2802ca9ef9ac7803190997045f60490/src/Tippy.js#L53

To make this wrapper more compatible with most React apps out there, I think `findDOMNode` is required.

**Comment by atomiks** [comment]
`findDOMNode` causes problems with context/React router ([see here](https://github.com/atomiks/tippyjs/issues/266)). Although, maybe that can be solved some way else.

**Comment by atomiks** [comment]
You're right. Only the `content` needs to use a ref, the child reference can remain as-is and be selected with `findDOMNode`.

**Comment by cusxio** [comment]
Just a heads up, `styled-components` v4 was just announced, and they are using the `forwardRef` API now. So your previous code will work now !

But overall, using `findDOMNode` is still better for compatibility.

**Comment by atomiks** [comment]
> But overall, using findDOMNode is still better for compatibility.

Yeah with `findDOMNode()` it "just works" when you have a component as a child. Otherwise you need to roll your own `withForwardRef` HOF

I think the latest version fixes the two main pain points that were found:

- Doesn't work with component as a child
- Doesn't work with React Router context
