### ISSUE TITLE
How to style target component?

### ISSUE THREAD

**Issue by BofEmptiness** [atomiks/tippy.js-react#30]
Is there a way to add some class or style to target element?

In my case i want to make every element with cursor: help.

**Comment by BofEmptiness** [comment]
Found a way to do it:
import Tippy from '@tippy.js/react'
import 'tippy.js/dist/tippy.css'
import React from 'react'

export const Tooltip = ({ children, ...rest }) => (
  <Tippy {...rest}>{React.cloneElement(children, { className: 'test' })}</Tippy>
)
Tooltip.defaultProps = {
  performance: true,
  animateFill: false,
  delay: [300, 0],
  animation: 'scale',
  theme: 'test',
  duration: [300, 300],
  distance: 5,
  maxWidth: '330px',
  sticky: true,
  touchHold: true
}

**Comment by atomiks** [comment]
Can't you just do this? The Tippy component is a generic container for any child element, it embraces composition

```jsx
<Tippy content="...">
  <button className="test">button</button>
</Tippy>
```

**Comment by BofEmptiness** [comment]
@atomiks yes, but i don't want to do it by hand in every component where i want tolltip. Maybe in future i will want to even delete this class, so it easy to do it in one place. Is there something wrong with my approach?

**Comment by atomiks** [comment]
Ah ok that makes sense, go for it
