### ISSUE TITLE
Guid

### ISSUE THREAD

**Issue by mrkenng** [atomiks/tippy.js-react#33]
Hi there! thanks for this react wrapper. I often get this and wonder if anyone else got this too?

```
VM3168:306 Uncaught TypeError: Cannot read property 'guid' of undefined
    at v (<anonymous>:306:1429)
    at removeEventListeners (popper.js:1070)
    at Popper.disableEventListeners (popper.js:1095)
    at Popper.disableEventListeners$$1 (popper.js:2515)
    at tippy.standalone.js:1718
    at tippy.standalone.js:1421
    at HTMLDivElement.listener (tippy.standalone.js:1448)
```

and 

```
VM3449:306 Uncaught TypeError: Cannot read property 'guid' of undefined
    at v (<anonymous>:306:1429)
    at removeEventListeners (popper.js:1070)
    at Popper.disableEventListeners (popper.js:1095)
    at Popper.disableEventListeners$$1 (popper.js:2515)
    at tippy.standalone.js:1718
    at tippy.standalone.js:1421
    at onTransitionEnd (tippy.standalone.js:1439)
    at onTransitionedOut (tippy.standalone.js:1419)
    at hide (tippy.standalone.js:1711)
    at destroy (tippy.standalone.js:1738)
    at show (tippy.standalone.js:1607)
    at tippy.standalone.js:1129
```

**Comment by atomiks** [comment]
Can you click on the line number where it happens?

**Comment by mrkenng** [comment]
1070 `  getWindow(reference).removeEventListener('resize', state.updateBound);`
1095`    this.state = removeEventListeners(this.reference, this.state);`
2515`      return disableEventListeners.call(this);`
1718`      tip.popperInstance.disableEventListeners();`
1421 `        callback();`
1448 `        callback();
`
These are the lines. I'm not sure if i'm using it correctly but could it be appendTo property? 

I'm using <Tippy appendTo={this.refs.example}><button ref="example">some text</a></Tippy>

**Comment by atomiks** [comment]
Appending it to the button itself might be a problem. Does it happen when you remove the `appendTo` prop? Maybe you need to append it to a wrapper outside the button

**Comment by mrkenng** [comment]
Ok I will try wrapping outside the button and get back to you. And yes, removing appendTo do not have this issue. Just tested it.

**Comment by mrkenng** [comment]
Wrapping outside show up this at times.

`Uncaught TypeError: Cannot read property 'contains' of undefined
    at mount (tippy.standalone.js:1380)
    at show (tippy.standalone.js:1632)
    at tippy.standalone.js:1129`

**Comment by mrkenng** [comment]
Hi, yes the ref existed before it renders.

--
Ken Ng

CONFIDENTIAL NOTICE: This e-mail and the information contained in this email is CONFIDENTIAL. If you have received this message in error or without the express direction, please notify the sender and delete this email immediately. Please consider the environment before printing this.

**Comment by atomiks** [comment]
Well it says it's `undefined` so it can't be. It should be some type of `Element` which has `.contains()`. `console.log` it out
