### ISSUE TITLE
using JSX as content breaks jest snapshots tests

### ISSUE THREAD

**Issue by florianbepunkt** [atomiks/tippy.js-react#34]
While this works …
`<Tippy content="Test">Component</Tippy>`

… passing JSX breaks all my jest snapshot tests
`<Tippy content={<span>Test</span>}>Component</Tippy>`

```
   Warning: An invalid container has been provided. This may indicate that another renderer is being used in addition to the test renderer. (For example, ReactDOM.createPortal inside of a ReactTestRenderer tree.) This is not supported.
        in span (created by Tooltip)
        in Tippy (created by Tooltip)
```

**Comment by florianbepunkt** [comment]
@atomiks great, thanks. In case anyone else has the same problem: I created a jest config file, that points to a setup file where I mock out the createPortal function

```
// jest.config.js
module.exports = {
  setupFiles: ["./.jest/storyshots-setup.js"]
};

// storyshots-setup.js
import ReactDOM from "react-dom";

ReactDOM.createPortal = jest.fn((element, node) => {
  return element;
});
```

**Comment by soullivaneuh** [comment]
@florianbepunkt Your solution did not work for me. However, I following this official doc part: https://github.com/storybookjs/storybook/tree/master/addons/storyshots/storyshots-core#example-with-react-testing-library

Make my storyshots working again.

Hope it will help for someone lost here like I was. :wink:

**Comment by ggravlingen** [comment]
@soullivaneuh this helped me, thanks!
