### ISSUE TITLE
onFocus popup doesn't pops 

### ISSUE THREAD

**Issue by Shubham-S-Yadav** [atomiks/tippy.js-react#36]
Can you show how to use trigger=focus, as it is not working in my case.
I want to handle tippy popup on onClick and also when arrow keys of keyboard focus on a particular cell.

**Comment by atomiks** [comment]
CodeSandbox reproduction? You might need `hideOnClick={false}`

**Comment by bigwoof91** [comment]
I'm experiencing the same issue... I tried using `hideOnClick` with no avail. Here's a snippet of the code, essentially:
```
    <Tippy
      arrow={true}
      content="Hi, I'm tooltip"
      interactive
      hideOnClick={false}
      placement="bottom-start"
      sticky
      trigger="focus"
      theme="light-border"
    >
      <span data-testid="trigger">
        {Trigger} // <-- prop
      </span>
    </Tippy>
```

**Comment by atomiks** [comment]
> I just want to show onClick, and hide the popper when a user clicks inside the popper

What's `interactive` prop for in this case?

**Comment by bigwoof91** [comment]
Menu items

> > I just want to show onClick, and hide the popper when a user clicks inside the popper
> 
> What's `interactive` prop for in this case?

To select menu items in the popper...

I'm building a popover menu component. So a user needs to be able to hover outside of the trigger, without the popper closing.

**Comment by atomiks** [comment]
I'm confused why you're adding a click listener to the popper to hide it if you also want to select things inside of it? It's difficult to understand what you're trying to achieve without a CodeSandbox example

**Comment by atomiks** [comment]
I understand now (last paragraph), makes sense. You want a single click interaction to occur still, but have it hide while doing it. 

I think there's a simple workaround: set `pointerEvents: 'auto'` on the `popper` node. You can use the `onCreate` prop

**Comment by bigwoof91** [comment]
> I understand now (last paragraph), makes sense. You want a single click interaction to occur still, but have it hide while doing it.
> 
> I think there's a simple workaround: set `pointerEvents: 'auto'` on the `popper` node. You can use the `onCreate` prop

Will give this a shot!

**Comment by bigwoof91** [comment]
> > I understand now (last paragraph), makes sense. You want a single click interaction to occur still, but have it hide while doing it.
> > I think there's a simple workaround: set `pointerEvents: 'auto'` on the `popper` node. You can use the `onCreate` prop
> 
> Thanks - Will give this a shot!

So that did not work, but I just set the `onclick`property on the popper node:

```
<Tippy
      ...
      interactive
      sticky
      trigger="click"
      onCreate={({ popper, hide }) => {
        popper.onclick = () => hide(150);
      }}
      ...
>
...
```
Not sure why setting `pointerEvents` didn't work - I think that `pointerEvents` is explicitly css property (`pointer-events`) and maybe it can't be attached to the node? I'm not too sure. But you pointed me in the right direction. Super helpful. 

As everyone else has been saying, thanks for the quick response!

**Comment by atomiks** [comment]
Sorry yeah my explanation was bad, I guess your method works fine anyway

I think I meant: `popper.style.pointerEvents = 'auto'` + remove `hideOnClick` prop + remove `interactive` prop
