### ISSUE TITLE
How to prevent wrapping?

### ISSUE THREAD

**Issue by NicoleRauch** [atomiks/tippy.js-react#37]
Hi,

I would like to display a rather long string, and I would like to show it in one line (in a very wide popup), but the contents gets wrapped... I have not found any settings with which I could keep it from wrapping.

Any ideas? Thank you very much in advance!

**Comment by atomiks** [comment]
Set `maxWidth` to something arbitrarily high. Note that the tooltip will not be larger than the horizontal width of the screen (e.g. on 320px wide screen, it will avoid being 300px wide I think (with margins))

**Comment by atomiks** [comment]
Set `maxWidth` to something arbitrarily high. Note that the tooltip will not be larger than the horizontal width of the screen (e.g. on 320px wide screen, it will avoid being larger than 300px wide (with margins))

**Comment by NicoleRauch** [comment]
Thank you very much for the quick response! I will look into it.

**Comment by NoMercy235** [comment]
Hello! Sorry for necro-posting, but my issue is related to this topic. I want to have a tooltip that can span the width of its parent. I've used the `appendTo="parent"` option to make the tooltip render as a child of the parent that hosts my text, but the tooltip container has it's `max-width` set to `calc(100vw - 10px)`, so setting `maxWidth` to `100%` will not do me any good. Is there a way to achieve what I want?

**Comment by atomiks** [comment]
Set `instance.popper.style.maxWidth = '100%'`

**Comment by NoMercy235** [comment]
That didn't work for me since the tippy container had `maxWidth: calc(100vw - 10px)` and so it would take up the entire width of the window instead of the width of the parent. I ended up solving this by giving the parent a `position: relative` which somehow stopped the expansion of the tippy container.

**Comment by atomiks** [comment]
But `instance.popper` is the parent container, so the style attribute should override it. Glad you solved it anyway :)

**Comment by NoMercy235** [comment]
My layout looked like this:
```html
<td style={{ position: 'relative' }}> <!-- this is where I set the position -->
  <div tippy-container-which-has-max-width-set-to-calc(100vw - 10px)>
    <div tippy-wrapper-where-user-defined-class-are-set>
      <my-content/>
    </div>
  </div>
</td>
```
