### ISSUE TITLE
Activating a trigger="manual" tooltip

### ISSUE THREAD

**Issue by claytongroth** [atomiks/tippy.js-react#38]
I am trying to activate a Tooltip in one static location on a page based on clicks elsewhere. Maybe I am just getting turned around. Could you provide/is there a minimal working example of how to do this?

Here's what I am working with to test it out. I'm just not sure where to go next based on previous issues and documentation. 
```
class Tooltest extends React.Component{
      constructor(props){
    super(props);
    this.myRef = React.createRef();
  }
  render(){
    return(
      <Tooltip
        ref={this.myRef}
        html={(
            <div dangerouslySetInnerHTML={{ __html: "There were once dinsoaurs"}}></div>
        )}
        trigger="manual"
       >
         <p>"TESTING"</p>
      </Tooltip>
    )
  }
}
```
Then I need to somehow call` this.myRef.current.tippy.show() ` from another component like so:

**Within `App` render method:**
```
someFunction(){
    //This will fire the tooltip based on a click in ClickMe
}
render(
  <div>
    <Tooltest />
    <ClickMe/>
  </div>
)
```

**Comment by atomiks** [comment]
There is no `html` prop with this component...

You need to use the `isVisible` prop: https://github.com/atomiks/tippy.js-react#react-specific-props

Set it to `true` when you want to show the tooltip.
