### ISSUE TITLE
Move prop-types package into peer dependency

### ISSUE THREAD

**Issue by saravanan10393** [atomiks/tippy.js-react#4]

**Comment by atomiks** [comment]
The prop-types package says to leave it in dependencies: https://www.npmjs.com/package/prop-types#how-to-depend-on-this-package

**Comment by atomiks** [comment]
e.g.

- https://github.com/reactjs/react-tabs/blob/master/package.json#L113
- https://github.com/aholachek/react-flip-toolkit/blob/master/package.json#L33
