### ISSUE TITLE
Changing dimensions of HTML tooltip

### ISSUE THREAD

**Issue by awcchungster** [atomiks/tippy.js-react#40]
How do I change the dimensions of the HTML tool tip? It's standard at 350px, and I want to make it wider. 

I tried the following, but not sure what the actual tag is supposed to be.

> <Tippy content={document.getElementById('hover')} placement="top" arrow= {true}  theme= {'light'} width= {'400px'} duration= {50} interactive= {true} animation= 'scale' offset={5}> {core_tags}</Tippy>

**Comment by atomiks** [comment]
`maxWidth` prop

**Comment by awcchungster** [comment]
Thanks for the super fast response!

I tried: 
`maxWidth= {'400px'}`

Is there specific syntax?

**Comment by atomiks** [comment]
First run `npm i @tippy.js/react@latest` (or equivalent if on Yarn) to ensure you have the latest `tippy.js` (3.3.0) dependency.

Number = pixels:
`maxWidth={400}`

String = with units if necessary
`maxWidth="50rem"`
`maxWidth="500px"`

**Comment by awcchungster** [comment]
Thanks so much for getting back so quickly! I really appreciate all the hard work maintaining and creating this.
