### ISSUE TITLE
How to use with css modules

### ISSUE THREAD

**Issue by Bobvantpadje** [atomiks/tippy.js-react#45]
I'm using css-modules in my project. I think this might be the reason why my tooltip does not contain any styling. I've imported the css in my `App.js` and implemented the tooltip as following: 
```
<Tippy content="Hello">
    <button>My button</button> 
</Tippy>
```
Do I have to follow some extra steps to get the tooltip working while using css-modules or am I doing something else wrong?

**Comment by atomiks** [comment]
I'm not familar with CSS modules :\
If you set up a test repo I can take a look

**Comment by KubaJastrz** [comment]
Haven't used it either, but don't you have to import the css file here and apply the imported class Name to some element? In your case you'd create a div with said className and pass it as content to Tippy

**Comment by Bobvantpadje** [comment]
I have just created a [repository](https://github.com/Bobvantpadje/testtooltip/tree/master/tooltipTest) with the tooltip and my current webpack config (using css modules and scss). 
 
As you can see there isn't any styling applied to the tooltip.

To run the project just run `yarn install` followed by `yarn dev`

**Comment by atomiks** [comment]
Did you forget this line?

```js
import 'tippy.js/dist/tippy.css'
```

**Comment by Bobvantpadje** [comment]
Just noticed that I forgot that in my newly created repository. If I do import it, the tooltip still doesn't include any styling.

**Comment by atomiks** [comment]
Kinda weird, the repo is not building for me/erroring out for some reason

It's not ideal but you could include the CSS from a CDN:

```html
<link rel="stylesheet" href="https://unpkg.com/tippy.js@3/dist/tippy.css">
```

**Comment by Bobvantpadje** [comment]
This does work, would be better if I could just use the regular css import. But for now this is fine. Thanks for your help!

**Comment by KubaJastrz** [comment]
After looking at the webpack config, I guess tippy css file is processed by css module loader: https://github.com/Bobvantpadje/testtooltip/blob/f077c60072d905949e910e17eef1effc8ea870da/tooltipTest/config/webpack.config.dev.js#L160-L173

Try adding `exclude: [/tippy\.css/],` to this rule.

**Comment by Bobvantpadje** [comment]
Excluding the node_modules and adding the extra module loader does kinda work. It adds the styling to the component, but it doesn't include any of my added settings (animation, arrowType). When I include the `<link rel="stylesheet" href="https://unpkg.com/tippy.js@3/dist/tippy.css">` the animation does work tho.

**Comment by KubaJastrz** [comment]
You've probably figured it out already, but you can just use mine rule and write custom tippy styles in any `*.global.css` file, so it's not "malformed" by CSS modules

**Comment by davidkutas** [comment]
I still think it is a serious issue as many devs use babel-css-modules https://github.com/gajus/babel-plugin-react-css-modules .

I solved it by excluding it in webpack as some commenters mentioned it above; but still, I think it's just a workaround.
