### ISSUE TITLE
Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

### ISSUE THREAD

**Issue by ReTWi** [atomiks/tippy.js-react#49]
After update to latest tippy i've started to get this error. Reproduction case:
Work's fine:
```
          <Tooltip content={'ам'}>
              <div>1</div>
          </Tooltip>
```

Got error:
```
          <Tooltip content={'ам'} >
                <Icon />
          </Tooltip>
```
or
```
          <Tooltip content={'ам'} >
            1
          </Tooltip>
```

Icon code:
```
export const Icon = props => (
  <svg {...props}>
     // svg image code
  </svg>
)
```

Tooltip code:
```
import Tippy from '@tippy.js/react'
import React, { useEffect, useState } from 'react'

export function Tooltip({ children, sharedContent, content, pure, ...rest }) {
  const [tip, tipSet] = useState(false)

  useEffect(() => {
    if (sharedContent) {
      switch (sharedContent) {
        case 'something':
          content = (
            <div>
               shared tips
            </div>
          )
      }
    }
    tipSet(content)
  }, [content])

  if (!tip) return false

  return (
    <Tippy content={tip} {...rest}>
      {pure
        ? React.cloneElement(children)
        : React.cloneElement(children, { className: 'tippy-target' })}  // change cursor to one with question mark
    </Tippy>
  )
}

Tooltip.defaultProps = {
  ignoreAttributes: true,
  animateFill: false,
  delay: [300, 0],
  interactive: true,
  animation: 'scale',
  theme: 'knigAm',
  duration: [300, 300],
  distance: 5,
  maxWidth: '330px',
  sticky: true,
  touchHold: true,
  a11y: false
}

```

Any thoughts to try?

**Comment by atomiks** [comment]
You need to use `forwardRef` if you're using a component as a child now. The internals were changed to remove `findDOMNode` which required this change

**Comment by atomiks** [comment]
I think a lot of people are ending up on this issue (if GitHub search is accurate!)

The full solution, including a workaround for legacy components, is available on the README: https://github.com/atomiks/tippy.js-react#component-children

**Comment by skychavda** [comment]
Here is the solution to this problem
[Solution of function component reference](https://github.com/reactjs/reactjs.org/issues/2120)

**Comment by webwanghongliang** [comment]
nice

**Comment by skychavda** [comment]
Here is another solution for this reference related issue in the functional component.
[Solved functional components issue](https://github.com/reactjs/reactjs.org/issues/2120)

**Comment by Slapbox** [comment]
For what it's worth I've had this message since implementing Tippy and pulled my hair out trying to find the cause when I was already using `forwardRef` before realizing that whatever the cause, there were no ill effects.

**Comment by obendesmond** [comment]
<h2>Another solution</h2>

<Child childRef={ref => (this.child = ref)} />

**Comment by obendesmond** [comment]
Take a look at this 
<b>[Page](https://github.com/reactjs/reactjs.org/issues/2120)</b>

**Comment by lowcrawler** [comment]
> Here is another solution for this reference related issue in the functional component.
> [Solved functional components issue](https://github.com/reactjs/reactjs.org/issues/2120)

That doesn't work because the linked solution is for when the parent and the child are both class components... not when the child is a functional component.

**Comment by skychavda** [comment]
> > Here is another solution for this reference related issue in the functional component.
> > [Solved functional components issue](https://github.com/reactjs/reactjs.org/issues/2120)
> 
> That doesn't work because the linked solution is for when the parent and the child are both class components... not when the child is a functional component.

@lowcrawler [Here](https://github.com/reactjs/reactjs.org/issues/2120#issuecomment-586200394) is the another solution with functional component hope this solution helps you. 😊

**Comment by kopax** [comment]
@skychavda I have replied to your example, I don't get why you wrap the `setText`, can you please tell? thanks!

**Comment by silverwind** [comment]
Any pointers on how to resolve this warning when using `children`? I'd like to wrap `Tippy` to pass some default props like this but I see no obvious way to `forwardRef` to `children`:

``` js
function Tip({children, ...props}) {
  // modify props
  return <Tippy {...props}>{children}</Tippy>
}
```

**Comment by JamesJGoodwin** [comment]
@atomiks could you please clarify and maybe add the code example to documentation on how to pass JSX to `content` prop?

I have the following component:
```ts
export const RangeDatePicker = (props: RangeDatePicketProps): JSX.Element => {
	const Calendar = () => (
		<div className="range-holder">
			<div className="range-header">
				<p>{props.type === 'there' ? 'Выберите дату отправления' : 'Выберите дату возвращения'}</p>
				<button className="no-backdate-ticket-needed">Обратный билет не нужен</button>
			</div>
			<div className="range-body">
				<DatePickerCalendar
					locale={ru}
					minimumDate={new Date()}
					maximumDate={moment().add(1, 'year').toDate()}
					date={props.values.startDate}
				/>
				<DatePickerCalendar
					locale={ru}
					minimumDate={props.values.startDate}
					maximumDate={moment().add(1, 'year').toDate()}
					date={props.values.endDate}
				/>
			</div>
		</div>
	)
	
	return (
		<Tippy
			content={<Calendar />}
			trigger="click"
			duration={0}
			interactive={true}
			theme={'light calendar'}
			popperOptions={{ modifiers: [{ ...noGpuAcceleration }] }}
			appendTo={document.body}
		>
			<DateInput type={props.type} segment={0} value={moment(props.values.startDate).locale('ru').format('D MMMM, ddd')} />
		</Tippy>
	)
}
```
And the problem is that I'm seeing the error no matter what I do. I tried to wrap `Calendar` subcomponent into a `forwardRef` but still there was an error. What am I doing wrong?
