### ISSUE TITLE
Error in snapshot testing

### ISSUE THREAD

**Issue by florianbepunkt** [atomiks/tippy.js-react#53]
Upgrading to Tippy 2 produces an error while snapshot testing with jest:

`TypeError: d.current.set is not a function at props (node_modules/@tippy.js/react/src/Tippy.js:61:38)`

Any advise?

**Comment by atomiks** [comment]
Can you post a reproduction case?

**Comment by florianbepunkt** [comment]
I put together a repro repo… https://github.com/florianbepunkt/tippy-repro

The tooltip is from the readme. It works fine in Storybook, but the snapshot test breaks because of the ref. This was working fine with the previous version.

**Comment by atomiks** [comment]
It looks like the DOM node ref is `null`, so the tippy instance doesn't get returned (actually an empty array does, it should probably throw an error if a non-valid element is found instead).

So.. I think you need to mock it somehow

**Comment by florianbepunkt** [comment]
@atomiks Thank you. In case anyone stumbles upon the same problem. Here I mock out set() and destroy on all elements since I use tippy in a lot of our components:

```
initStoryshots({
  config: ({ configure }) => configure(loadStoriesForST, module),
  suite: "Snapshot Testing",
  test: snapshotWithOptions({
    createNodeMock: element => {
      return {
        ...element,
        focus() {},
        set() {},
        destroy() {}
      };
    }
  })
});

```
