### ISSUE TITLE
Feature request: support for className prop

### ISSUE THREAD

**Issue by benkeen** [atomiks/tippy.js-react#55]
I realize this was brought up in other tickets and you can get around it by passing a `theme` prop, but within the React ecosystem passing a `className` prop is pretty much a standard - everyone expects it when consuming components. Using `theme` lets you get add your class string to the DOM, but because it dynamically appends a `-theme` suffix to the name, it's unexpected. 

Just FYI, my particular use-case is that we're integrating this component into an existing system with test automation. Our automation team uses a convention to target DOM nodes via classes, so because it appends the `-theme` we're having to do a little extra legwork to get around the problem.

Thanks!

[Edit: if the maintainer of this lib approves the idea, I'm happy to put in a PR]

**Comment by atomiks** [comment]
You make good points! Feel free to make a PR 🙂

**Comment by benkeen** [comment]
Thanks @atomiks! I'll work on this tonight. :)

**Comment by atomiks** [comment]
In case you're stuck, I think it'll be something like this

```js
// mount useEffect
const instance = tippy(...)
instanceRef.current = instance
if (props.className) {
  const { tooltip } = instance.popperChildren
  props.className.split(' ').forEach(name => {
    tooltip.classList.add(name)
  })
}
```

With an equivalent diff check for add/remove for the update useEffect

**Comment by benkeen** [comment]
Oh haha, rats! I was actually going to add it to the underlying tippy.js lib, like so:
https://github.com/benkeen/tippyjs/commit/e7d86305bca8966472e45e27c78fd01d26779fc2

Seems like it might be useful there too (and it doesn't add much, if any code, since I'm re-using the same method as `theme`), but I'm happy to make the change as you suggested instead.

**Comment by atomiks** [comment]
I don't think it's necessary as an option in the vanilla library since I haven't seen requests for it in the native repo, and the user can add their own classes if they wanted (as seen above) as the instance exposes all the elements for them, which is how we can do it in the React wrapper. A declarative option is nice, but not worth it for extra code imo

**Comment by benkeen** [comment]
Sounds good. I'll take another look tonight.
