### ISSUE TITLE
scheduleUpdate() of Popper is continuously called when wrapper of target is scrolled

### ISSUE THREAD

**Issue by oh3vci** [atomiks/tippy.js-react#6]
I found that the performance was falling when I scrolled the page included Tippy component.
And the reason was that scheduleUpdate() of Popper was continuously called in the part of update.
It should be called disableEventListeners() of Popper.

```javascript
componentDidUpdate() {
/*
    this.tip.set({
        ...getNativeTippyProps(this.props),
        content: this.getContent()
    });
*/
}
```

**Comment by atomiks** [comment]
Problem is here (`disableEventListeners()` not called after creation): https://github.com/atomiks/tippyjs/blob/master/src/js/createTippy.js#L713

This means it's an issue with `tippy.js` and not this component.

Releasing a patch soon with several fixes.

**Comment by atomiks** [comment]
Update to `tippy.js@3.0.2` and it should be fixed.
