### ISSUE TITLE
option to use render props to pass ref to custom components

### ISSUE THREAD

**Issue by robjtede** [atomiks/tippy.js-react#61]
Some third party components (in my case, the `Field` component from Formik) use a custom name for their ref prop (eg. `innerRef)`. Having an option to use the render prop pattern to pass the ref down could ease some of these use cases; the alternative being rolling your own wrapper component that uses `forwardRef`.

**Comment by atomiks** [comment]
Shouldn't Formik publish a new major that uses `forwardRef` like `styled-components` v4?

**Comment by robjtede** [comment]
I had a feeling that would be the response :P it's not a huge problem I just have a reasonable number of dependencies that aren't likely to get updated as quickly as Formik and would need wrappers for most of them.

Feel free to close.

**Comment by robjtede** [comment]
closing, wrapping things in spans is almost always enough to alleviate this
