### ISSUE TITLE
passing `popperOptions: undefined` crashes page

### ISSUE THREAD

**Issue by robjtede** [atomiks/tippy.js-react#62]
NB: This seems to be an issue within tippy itself but I thought I'd make an issue here in case a check/default on the component side is enough.

I created a wrapper around Tippy to provide custom defaults but found that the page became unresponsive when hovering over the target element; page using 100% cpu according to devtools. This started recently, so possibly a tippy v4 regression.

Since the wrapper passes undefined to Tippy when it is not explicitly set by the component, it is necessary to use `{}` as the default param.

Working:
```jsx
<Tippy content="hello">
  <span>works</span>
</Tippy>
```

Breaking:
```jsx
<Tippy content="hello" popperOptions={undefined}>
  <span>breaks</span>
</Tippy>
```

**Comment by atomiks** [comment]
This probably broke it: https://github.com/atomiks/tippyjs/commit/294351a8aab0925912a1d6887d3fc7583215c637

Would need a check `popperOptions && popperOptions.onUpdate`

**Comment by robjtede** [comment]
wouldn't that throw if `popperOptions` was undefined there

**Comment by atomiks** [comment]
It's a destructured property higher in the scope. 

Is this high priority or can you set it as an object explicitly instead of undefined for now?

**Comment by robjtede** [comment]
no this is easily solved by just using `{}` as the default prop
