### ISSUE TITLE
Styling the arrow using styled components

### ISSUE THREAD

**Issue by VStas** [atomiks/tippy.js-react#64]
Hello! I'm trying to change the color of the arrow. However, I need to check the `x-placement` property of element with class `.tippy-popper` (as it is written in doc https://atomiks.github.io/tippyjs/themes/#styling-the-arrow )

I want to change the color using styled components without adding global styles. But the className that I pass to `<TippyTooltip>` component is only applied to `.tippy-tooltip` div which is a child of 
`.tippy-popper`. There's no way I can check the `x-placement` property of `.tippy-popper`. Maybe there should be another className prop that will add my additional class to `.tippy-popper` ? Or maybe there's another way I can solve this problem

**Comment by atomiks** [comment]
Just wondering how you're using it with styled-components?

Maybe you should be able to pass an object? Like:

```jsx
<Tippy className={{
  popper: 'name',
  tooltip: 'name',
  arrow: 'name', // maybe as well?
  content: 'name', // maybe as well?
}}>
  <button />
</Tippy>
```

If it makes sense feel free to make a PR!

**Comment by atomiks** [comment]
Looks like that doesn't work with SC. Might have to bump the major and apply `className` to the popper element instead? `:/`

**Comment by atomiks** [comment]
Ok there's no need to bump the major (thankfully). We can add a `popperClassName` instead, which can be applied to the parent, and use this in SC:

```jsx
const TomatoTippy = styled(({ className, ...props }) => (
  <Tippy popperClassName={className} {...props} />
))`
  .tippy-tooltip {
    background: purple;
  }

  /* etc */
  &[x-placement^='bottom'] {
    .tippy-arrow {
      border-bottom-color: purple;
    }
  }
`
```

**Comment by atomiks** [comment]
Run

```bash
@tippy.js/react@latest
```

To get the latest `tippy.js@4.2.0` update which includes this feature now! 

Usage with `styled-components`:

```js
const PurpleTippy = styled(Tippy)`
  &[x-placement^='bottom'] {
    .tippy-arrow {
      border-bottom-color: purple;
    }
  }
`
```
