### ISSUE TITLE
Cannot change the animation

### ISSUE THREAD

**Issue by DarkHollow** [atomiks/tippy.js-react#66]
Hello, I am having problems with Tippy.

First of all, I am using it in [nextjs](https://github.com/zeit/next.js/) and I don't know if this is the cause of my problems. I am adding Tippy to a `span` and it is working, the problem is that I cannot change the animation no matter which animation I set

```javascript
<Tippy
    content={<span>Circle</span>}
    animation={'shift-away'}>
    <span className="circle"></span>
</Tippy>
```
By the way, the animation that I always see is apparently `fade`.

Other thing I am noticing is that the animation only works when showing up but when on mouse out the Tippy just disappears without animation.

I tried adding arrows but then there is not animation at all (mouse in/mouse out).

**Comment by atomiks** [comment]
Hmm I've never experienced this before (with Next either).

You'll need to reproduce it
https://codesandbox.io/s/64q0l051vk

**Comment by DarkHollow** [comment]
I was trying to reproduce it but I can't, works fine. I tried in all my project pages, including in index.js (it is pretty clean) to see if some component was messing with Tippy but in all cases doesn't work correctly.

I am trying to upgrade nextjs to last version.

Thank you for your help.

**Comment by DarkHollow** [comment]
I found the problem, for some reason (test animations and so) I left this in my css:

```css
div {
  transition: height 0.5s ease-in-out;
}
```
and that was conflicting with the Tippy animations.

I'm sorry for not investigating a little more before opening the issue. Thank you for the help and of course for Tippy!
