### ISSUE TITLE
Issue with className prop passing with Styled Components 

### ISSUE THREAD

**Issue by jamesmosier** [atomiks/tippy.js-react#68]
Thanks for a great project! Is there any insight into this warning I receive from styled-components when using it with Tippy React?

`
It looks like you've wrapped styled() around your React component (Popover), but the className prop is not being passed down to a child. 
No styles will be rendered unless className is composed within your React component.
`

[Here is a codesandbox](https://codesandbox.io/s/84j0o6pwj8) with the warning. Oddly enough, the example works as expected. I am wrapping the `<Tippy />` component in a styled-component and that in turn styles the `.tippy-tooltip` element.

The warning is due to the fact I am passing in a custom component for `content` but my custom component is not receiving the props from styled-components (but I don't **need** it to). 

For now I'm just passing `suppressClassNameWarning` into `StyledPopover` (in my example).

Any thoughts would be great! Thanks again!

**Comment by BrianMitchL** [comment]
I am also getting this warning. How were you able to suppress it? I don't see any `supressClassNameWarning` in your codesandbox example.

**Comment by jamesmosier** [comment]
Hi @BrianMitchL, I didn't include it in the example because I didn't want to show my workaround, rather the issue. But if you put `suppressClassNameWarning` on the `StyledPopover` component, that'll hide the warning:

`<StyledPopover content={<InnerComponent />} suppressClassNameWarning>`

**Comment by BrianMitchL** [comment]
Fair! Hmm, I get an error from the wrapped Tippy when trying that:
```
Error: [tippy]: `suppressClassNameWarning` is not a valid option`
```

**Comment by jamesmosier** [comment]
Oops, sorry @BrianMitchL, here is a forked [codesandbox](https://codesandbox.io/s/y2845jv8j1) with it working. You have to exclude `suppressClassNameWarning` from being passed into Tippy. So inside `Tippy.js` I pass all props except for that.

**Comment by BrianMitchL** [comment]
Oh, of course, thanks!

**Comment by atomiks** [comment]
Sorry for not checking this one earlier.

I think it's a bug in `styled-components` because it's not checking the Portal container for children with the className, only the direct tree elements.

**Comment by atomiks** [comment]
I guess if you want this fixed, feel free to make some noise in the `styled-components` issue I linked
