### ISSUE TITLE
Hiding all tooltips except the last one

### ISSUE THREAD

**Issue by elya158** [atomiks/tippy.js-react#7]
Is it possible to hide all other tooltips when one is showing or maybe call the static method hideAllPoppers for the tooltip show event?
When there are multiple tooltips on a page and the animation duration is long, it leaves a trail of tooltips, I want to be able to "destroy" the events of the other tooltips and only show the last target that was supposed to show (Like the solo option in qtip2).

**Comment by atomiks** [comment]
> Is it possible to hide all other tooltips when one is showing or maybe call the static method hideAllPoppers for the tooltip show event?

Something like this?

```js
import tippy from 'tippy.js'

Tippy.defaultProps = {
  onShow: () => {
    tippy.hideAllPoppers()
  }
}
```

**Comment by elya158** [comment]
Thanks your last edit seems to be the best solution, that way only one popper is visible at a time.

**Comment by mengqing** [comment]
This solution doesn't seem to work for the latest version. Is there an alternative solution?

**Comment by atomiks** [comment]
```js
import { hideAll } from 'tippy.js'
```

**Comment by kschiffer** [comment]
Appears to me like also this does not work anymore. Any alternative currently?

**Comment by kschiffer** [comment]
Actually it does still work, had an issue in my setup there. 

Just for the record there's an alternative way to achieve this without needing another import:

```javascript
// Outside the scope of the component
let currentInstance

…
  
// Inside the component 
  const handleShow = React.useCallback(
    instance => {
      if (currentInstance) {
      	// `unmount()` will skip the exit-animation as well which is usually desired
      	// in this scenario. Alternatively, use `hide()`
        currentInstance.unmount()
      }
      currentInstance = instance

      if (props.onShow) {
      	onShow(instance)
      }
    },
    [props.onShow],
  )
return <Tippy {...props} onShow={handleShow} />
```

This should ensure that only one tooltip can ever be visible at a time.

**Comment by els-mikhail-molchanov** [comment]
Please note that if you're using headless tippy the right place to import `hideAll()` helper from is **`tippy.js/headless`**, not `tippy.js`.
