### ISSUE TITLE
Not compatible with babel-plugin-react-element-info

### ISSUE THREAD

**Issue by IHarryIJumper** [atomiks/tippy.js-react#70]
I use **babel-plugin-react-element-info** plugin in my project.
But seems like **Tippy** doesn't like it.

> Error: [tippy]: `data-qa-node` is not a valid option

**Comment by atomiks** [comment]
What does this plugin do? Seems like it's passing that prop to `<Tippy>` but it won't be accepted

**Comment by atomiks** [comment]
I think if you create a wrapper component that strips those props and forward the valid ones to `<Tippy />`, it will work.

```js
import Tippy from '@tippy.js/react'

function TippyProxy(props) {
  const validProps = { ...props }
  delete validProps['data-qa-node']
  delete validProps['data-qa-file']
  return <Tippy {...validProps} />
}

export default TippyProxy
```

If those props should be forwarded to the reference DOM node, you can clone the `children` prop and add them inside this proxy I guess

**Comment by IHarryIJumper** [comment]
I'll try, thanks!
