### ISSUE TITLE
Use React Component as content prop

### ISSUE THREAD

**Issue by iamtekeste** [atomiks/tippy.js-react#75]
Thank you for making this dope component!

I would like to pass a react component as value to the `content` prop. Is that possible? If not, I would be grateful if you could suggest a workaround of sorts.

```jsx
import UnsplashPicker from './UnsplashPicker';

...

<Tippy content={<UnsplashPicker />} >
  <button>
    Change Image
  </button>
</Tippy>
```
Thank you.

**Comment by atomiks** [comment]
Yes you can pass a tree of React elements

**Comment by iamtekeste** [comment]
I wanted to use a React Component that has all the life cycle methods too.
I think React Elements are simple `divs` and `buttons`.

Correct me if I am wrong.

**Comment by atomiks** [comment]
"React element" is a plain object that describes both DOM nodes and component instances, React will render them both appropriately inside the tippy
