### ISSUE TITLE
[Potential deprecation] Rename isVisible / isEnabled props to visible / enabled

### ISSUE THREAD

**Issue by atomiks** [atomiks/tippy.js-react#76]
The `is` prefix is common for things that are only boolean values, and it matches up with the names in `instance.state`. However, all the other props, including boolean-only ones, don't have this prefix (for example, `interactive`), because there was the potential to include other values values in the future (e.g. `followCursor` used to be boolean-only until the string values were added recently).

Should we rename these two React props without the `is` prefix to match the other native props? This is only a deprecation and I don't think there should be an annoying warning for it.

### Basic example

```jsx
// These boolean props now have the same naming scheme
<Tippy interactive visible>
  <button />
</Tippy>
```

**Comment by KubaJastrz** [comment]
Adding more possible values to existing boolean-only props (such as the `followCursor` case) can also cause breaking changes, ie. when user has non-strict comparison `==`.

Personally, I'd prefer having names that suggest the type, such as `is`/`on` prefixes, so it's more clear and prone to less errors if you're not using TypeScript.

**Comment by atomiks** [comment]
> Adding more possible values to existing boolean-only props (such as the followCursor case) can also cause breaking changes, ie. when user has non-strict comparison ==.

Didn't consider that really. Doesn't seem like anyone had a problem with it though.

I'm never going to rename the native props because the churn isn't worth it, they're shorter to type, and because there are 3 different types of prefixes you can use for booleans:

- `isInteractive`
- `hasArrow`
- `shouldHideOnClick`

### Pros

-  `enabled` / `visible` are shorter to type out since you don't need to use camelCase and press shift (very minor inconvenience obviously 😅)
- Matches the native `tippy.js` options
- Matches boolean HTML attributes (`disabled` / `checked`, etc)

### Cons

- Slight churn in this library (though I won't be releasing a major for a while probably, until Popper v2)
- Lose type hints in the prop name itself

Worth it or not? 🤔

**Comment by KubaJastrz** [comment]
I think it's good to have one consistent pattern. And if you want to stick to the existing names, then that's fine too.

**Comment by atomiks** [comment]
> I think it's good to have one consistent pattern

Yeah this is the main issue, there's inconsistency currently - they only match the names in `instance.state`, but that's not really relevant for this wrapper.

So, here's my final justification:

- The native `tippy.js` options don't have this boolean naming convention, so there's inconsistency in the props naming. This is the most valid reason for changing it, I think

- Boolean attributes don't have this convention. HTML attributes, aka `disabled`, `checked`, etc, don't have this prefix. React's props appear as attributes when using the component in JSX (even if they are just objects once compiled), so they're effectively the same, and should match the naming scheme.

- Also, since `<Tippy prop={true} />` has the shorthand `<Tippy prop />`, I feel like it works better as an adjective. `<Tippy visible />` makes a bit more sense than `<Tippy isVisible />` because to me, the second seems to be asking a question more and begs the value (`is it visible? [value]` vs `visible: true`). Although both can be used interchangeably.

- I dislike capital `I` in `Is` when you use the `set` prefix for Hooks (lol):

```jsx
const [isVisible, setIsVisible] = useState(true)
const [visible, setVisible] = useState(true)
```

Just feel like it's cleaner the second way.

Given the above points, I believe it's worth changing it. I will open a PR later

**Comment by KubaJastrz** [comment]
> `<Tippy prop={true} />` has the shorthand `<Tippy prop />`

Maybe that's why in TypeScript the shorthand it is disallowed, so you can use more verbose naming pattern without any concerns :smile:
