### ISSUE TITLE
When styling with css zoom property, the tooltip position isn't above zoomed element

### ISSUE THREAD

**Issue by elya158** [atomiks/tippy.js-react#80]
When wrapping Tippy around an element that has the css zoom property, the tooltip's position isn't in the correct place, instead of being relative to the element, it's position is somewhere far away from it.

_**Example:**_
`<Tippy content="tooltip test">
  <span style={ { zoom: '125%' } }>test</span>
</Tippy>`

Do you have a quick solution for this?

**Comment by atomiks** [comment]
`zoom` is a non-standard property that should be avoided, use `transform: scale(1.25)` instead. This would be a Popper.js issue as well I think

**Comment by YasserKa** [comment]
If you are in a position that you are forced to use zoom. You can make tippy work by adding
```
/* css */
[data-tippy-root] {
    width: max-content;
}
```
&
```
// tippy attribute
appendTo: 'parent',
```
I did that and it worked fine with the state I was in. If it didn't work, you might need to do some little alterations.

**Comment by hiepnq294** [comment]
Hi @atomiks , in safari, ```zoom: 2``` works well to scale element, but ```transform: scale(2)``` makes the UI blurry (in only safari), so can you take a look at this again?
