### ISSUE TITLE
Unmount content component after hide/close

### ISSUE THREAD

**Issue by BrianMitchL** [atomiks/tippy.js-react#82]
The content component instance remains in memory/mounted across open/closes of the popover. This is fine, and probably expected for simple non-interactive tippys, but for small forms and other uses, it makes tippy more difficult to use. Currently, I'm resetting the component state when `isOpen` switches from false to true in a controlled instance of Tippy. Is there a better way to do this?

**Comment by atomiks** [comment]
Can you use a state variable like:

```jsx
const [mounted, setMounted] = useState(true);

return (
  <Tippy
    content={mounted ? <Form /> : null}
    onShow={() => setMounted(true)}
    onHidden={() => setMounted(false)}
  >
    <button />
  </Tippy>
);
```

**Comment by BrianMitchL** [comment]
That works great, thanks! I somehow missed the `onShow`/`onHidden` calls. The TypeScript definitions don't allow `null` for the `content` prop (see #21), but using an empty fragment works as an alternate `content={mounted ? <Form /> : <></>}`
