### ISSUE TITLE
Render prop for target

### ISSUE THREAD

**Issue by anault** [atomiks/tippy.js-react#83]
It'd be useful to have a render prop for the target, which could receive the current state as arguments à la [React Router](https://reacttraining.com/react-router/core/api/Route/render-func):

```jsx
import Tooltip from "@tippy.js/react";

<Tooltip
  trigger="click"
  content={"this is a tooltip"}
  render={({ visible }) => (
    <button>
      {visible ? "close tooltip" : "open tooltip"}
    </button>
  )}
/>
```

Currently, afaik the only way we can do this is by raising the visibility state up in the parent component and have a controlled tooltip which is fine in many case, but redundant/unwanted in some.

Tippy is awesome btw - keep up the good work!

**Comment by anault** [comment]
Another workaround would be:

```jsx
<Tooltip
  trigger="click"
  content={"this is a tooltip"}
  onShown={() => setVisible(true)}
  onHidden={() => setVisible(false)}
>
  <button>
    {visible ? "close tooltip" : "open tooltip"}
  </button>
</Tootip>
```

But still, the render prop would be awesome!

**Comment by atomiks** [comment]
Seems useful indeed, want to take a crack at a PR for it?

**Comment by Vivalldi** [comment]
@anault - What if you went for children being either a function or a react node?

```jsx
import Tooltip from "@tippy.js/react";

<Tooltip trigger="click" content={"this is a tooltip"}>
  {visible => (
    <button>
      {visible ? "close tooltip" : "open tooltip"}
    </button>
  )}
</Tooltip>
```

Even better pass the instance as the argument

```jsx
import Tooltip from "@tippy.js/react";

<Tooltip trigger="click" content={"this is a tooltip"}>
  {instance => (
    <button>
      {instance.isVisible ? "close tooltip" : "open tooltip"}
    </button>
  )}
</Tooltip>
```

**Comment by atomiks** [comment]
I think this is not feasible because the instance is only available after mount (`useLayoutEffect`), therefore the child target will only appear after mount, making it disappear during SSR phase. The workaround seems to be the best solution.
