### ISSUE TITLE
tippy dropdown

### ISSUE THREAD

**Issue by humbertqz** [atomiks/tippy.js-react#86]
Hi, is it possible to make a dropdown like in tippy.js? i could not find an example. 

![Screen Shot 2019-04-26 at 3 59 25 PM](https://user-images.githubusercontent.com/875269/56836282-626abe80-683c-11e9-9de4-043cec1ee66d.png)

Thanks for your help.

**Comment by atomiks** [comment]
That dropdown is made with this package :p

```jsx
import 'tippy.js/themes/light-border.css'

<Tippy 
  content={<DropdownContent />} 
  placement="bottom" 
  animation="fade" 
  arrow={true} 
  theme="light-border"
  trigger="click"
  // Need to ensure it can be tabbed to directly after with no clipping issues
  appendTo="parent"
  onMount={() => setAriaExpanded('true')}
  onHide={() => setAriaExpanded('false')}
>
  <button aria-haspopup="true" aria-expanded={ariaExpanded}>
    Dropdown
  </button>
</Tippy>
```

**Comment by humbertqz** [comment]
Thanks @atomiks i will try this.

**Comment by aaronjedwards** [comment]
@atomiks how could you modify this example to hide the tooltip/popover when something within `<DropdownContent/>` is pressed? 

For example, I have an instance where I am using this as a popover menu with `trigger='click'` and `interactive='true'` which allows me to click the content elements, but obviously does not trigger the popover to close.

Any thoughts would be appreciated! Thanks.

**Comment by atomiks** [comment]
You could grab access to the instance via the `onCreate` prop, then pass it down to `<DropdownContent />` 

https://codesandbox.io/s/festive-flower-5h4uz

```jsx
function App() {
  const [instance, setInstance] = useState(null);

  return (
    <Tippy 
      content={instance ? <DropdownContent hide={instance.hide} /> : ''}
      onCreate={setInstance}
    >
      <button />
    </Tippy>
  );
}

function DropdownContent({hide}) {
  return <button onClick={hide} />;
}
```

Inside `<DropdownContent />` you can now call `hide()` upon clicking something. 

(Note: that `instance` is not a class that uses `this`, so you can safely destructure every property or method on it and not run into problems).
