### ISSUE TITLE
Event delegation

### ISSUE THREAD

**Issue by wahlstedt** [atomiks/tippy.js-react#87]
Tippy is great and I've used it in several places in my project already. I now want to add tippys to the rows of a table with hundreds of rows, so using event delegation seems like a good idea. However, I can't get it to work for a couple of reasons:

First, I can get the tippys to show up by setting the `target` prop and a static `content`. But randomly the tippys will start showing up empty while I move the pointer over the table rows.

Secondly, I want to display a custom component instead of text in the tippy. How would I pass an id back when used with event delegation so I can add it as a prop to my component?

**Comment by atomiks** [comment]
Event delegation does not work well with the React component model. Have you looked into windowing  as a way to boost performance instead (that's assuming you're actually having performance issues currently without event delegation)?

**Comment by wahlstedt** [comment]
I started trying to implement event delegation since it looked like the best fit for my use case so I don't know if there will be performance issues without it. Using windowing is probably a good alternative, but probably much more complicated. I guess I'll have to bite the bullet on that one... Thanks for the quick reply though!
