### ISSUE TITLE
Add data-test prop for tooltip's content

### ISSUE THREAD

**Issue by devtsaki** [atomiks/tippy.js-react#89]
I want to add a data-test prop for the tooltip's content and right now there is not such prop exposed to the user of tippy. I know I can add an element wrapper around my content, but that is going to put an unnecessary div in DOM.
Would exposing data-test prop be possible?

**Comment by atomiks** [comment]
How will you `querySelector` the content if it's rendered in a portal?

You can grab the instance with `onCreate` and access the `instance.popperChildren.content` element to test the content.

**Comment by devtsaki** [comment]
The truth is that I am using tippy for a reusable popover component and I wouldn't want to expose the internal implementation of the component to the consumer. Also I would like to make it easier for someone writing end-to-end tests, by giving them the `data-test` selector ready to use.
For my unit tests I am using `react-testing-libary` and trigger the popover with `fireEvent.click()`. Then I query the text inside tippy's content with `getByText`.
I guess it's the consumer's responsibility to pass a div with whatever `data-test` selector he wants.

**Comment by atomiks** [comment]
Uhmm I forgot to reply lol

```jsx
function Tippy2(props) {
  const dataTest = props['data-test'];
  delete props['data-test'];

  function onCreate(instance) {
    if (props.onCreate) {
      props.onCreate(instance);
    }

    const {content} = instance.popperChildren;
    // Something last. I see that tippy's content is wrapped in a div. 
    // Is there a way I can add an attribute on that div?
    const containerDiv = content.firstElementChild;
    // Or content node itself...
    content.setAttribute('data-test', dataTest);
  }

  return <Tippy {...props} onCreate={onCreate} />;
}
```

**Comment by devtsaki** [comment]
Don't worry atomiks. Thank you for your reply and your time. Keep up the good work.
I will close this ticket now.
