### ISSUE TITLE
Enabled prop is broken

### ISSUE THREAD

**Issue by luskin** [atomiks/tippy.js-react#90]
According to the documentation, `enabled` is a valid boolean prop to Tippy, however it crashes our app.

Our code:

```
     <Tippy
        key={source.id}
        content={...THE CONTENT CODE...}
        trigger={'click'}
        enabled={!source.isDefault}
        arrow
        arrowType={'round'}
        theme={'light'}
        animateFill={false}
        interactive={true}
        onShow={() => setSelectedSource(source.id)}
        onHide={() => setSelectedSource(null)}
      >
```

The error thrown:
`[tippy]: 'enabled' is not a valid option`

**Comment by luskin** [comment]
Just needed to update tippy.... closing.

**Comment by atomiks** [comment]
Might need to do some checks to make sure you have the correct `tippy.js` version in the future to prevent this?
