### ISSUE TITLE
Question about nested tooltips

### ISSUE THREAD

**Issue by mviens** [atomiks/tippy.js-react#92]
I have tried creating a nested tooltip, but the nested one does not display.  I would appreciate any help.

```
<!DOCTYPE html>
<html lang='en'>
    <head>
        <meta charset='UTF-8'/>
        <title>Tippy Playground</title>
        <style>
            html,body {font-family:Roboto,sans-serif;font-size:1em;}
            tt {color:royalBlue;font-size:1.4em;}
            button {margin:.5em;padding:.5em;}
            #box {align-items:flex-start;display:flex;flex-wrap:wrap;justify-content:center;}
            .gap {width:2em;}
            .help {cursor:help;}
            .hide {display:none;}
            .nested {border-bottom:2px dotted #333;}

            .tippy-tooltip.hs-theme {background-color: #ffecb3;border: .1em solid #ef5350;border-radius: 1em;color: #333;}
            .tippy-tooltip.hs-theme[data-animatefill] {background-color:transparent;}
            .tippy-tooltip.hs-theme .tippy-backdrop {background-color:#ffecb3;}
            .tippy-tooltip.hs-theme[x-placement^='top'] .tippy-arrow {border-top-color:#ef5350;margin-bottom:-.15em;}
            .tippy-tooltip.hs-theme[x-placement^='bottom'] .tippy-arrow {border-bottom-color:#ef5350;margin-top:-.15em;}
            .tippy-tooltip.hs-theme[x-placement^='left'] .tippy-arrow {border-left-color:#ef5350;margin-right:-.15em;}
            .tippy-tooltip.hs-theme[x-placement^='right'] .tippy-arrow {border-right-color:#ef5350;margin-left:-.15em;}
        </style>
    </head>
<body>
    <h3>This is a simple test for Tippy.js tooltips</h3>
    <div id='box'>
        <button class='t1 help'>Tooltip #1</button>
        <button class='t1 help'>Tooltip #1</button>
        <span class='gap'></span>
        <button class='t2 help'>Tooltip #2</button>
        <button class='t2 help'>Tooltip #2</button>
        <span class='gap'></span>
        <a href="#" class="myTip3 help">Nested</a>
    </box>

    <div class='hide'>
        <main id='myTip1'>
            A simple tooltip that contains very basic HTML, but is long enough to cause a line wrap - <tt>something special here</tt>.
        </main>
        <main id='myTip2'>
            This is tip #2.
        </main>
        <div id="myTip3">
            This is a regular tooltip, but with the addition of a <span class='nested help'>nested</span> tooltip.
        </div>
        <div id="myTip3-nested">
            This is a nested tooltip.
        </div>
    </div>

    <script src="https://unpkg.com/popper.js@1"></script>
    <script src="https://unpkg.com/tippy.js@4"></script>
    <script>
        tippy.setDefaults({
            allowHTML: true,
            animation: 'scale',
            arrow: false,
            delay: [100, 300],
            flip: true,
            flipBehavior: ['bottom', 'top'],
            interactive: true,
            maxWidth: '30em',
            multiple: true,
            placement: 'bottom-end',
            theme: 'hs',
        });
        tippy.group(
            tippy('.t1', {
                content: document.querySelector('#myTip1').innerHTML,
                placement: 'bottom-start',
            })
        );
        tippy('.t2', {
            content: document.querySelector('#myTip2').innerHTML,
        });
        tippy('.myTip3', {
            arrow: true,
            content: document.querySelector('#myTip3').innerHTML,
        });
        tippy('.myTip3 .nested', {
            arrow: true,
            content: document.querySelector('#myTip3-nested').innerHTML,
        });
    </script>
</body>
</html>
```

**Comment by atomiks** [comment]
This is the repo for the React wrapper not the vanilla lib 😅 

Anyway, I'm not really sure what your code is supposed to be doing, but you the inner elements need to be part of a content element for the main parent tippy. 

```js
const content = document.createElement('div')

// 3 inner buttons with their own tippy
for (let i = 0; i < 3; i++) {
  const button = document.createElement('button')
  button.textContent = 'Text'
  content.appendChild(button)

  tippy(button, {
    content: "I'm a Tippy tooltip!",
  })
}

tippy('.myTip3', {
  content,
})
```

Extra logic is required to handle an edge case related to the parent tippy hiding which causes the child tippy to become disjointed from its reference element if it was also showing.... I'm going to document it soon

**Comment by guidupuy** [comment]
> Extra logic is required to handle an edge case related to the parent tippy hiding which causes the child tippy to become disjointed from its reference element if it was also showing....

I'm having this exact problem, has this been documented somewhere? Any pointer would be greatly appreciated, thanks!

**Comment by atomiks** [comment]
As long as the nested interactive tippies are being appended to each other (rather than to the body for example), it should work without any problem in the latest version

**Comment by guidupuy** [comment]
That solved it, thanks! I discovered another issue though related to styling: because you use `[x-placement^='bottom'] .tippy-arrow ` instead of [x-placement^='bottom']>.tippy-arrow`, if you have nested tippies with different placements the arrow of the nested tippy isn't styled correctly (styles for the arrow of the parent tippy apply).

**Comment by atomiks** [comment]
The latest version has used those child selectors for a while (and `data-placement` instead of `x-`), are you on latest?

**Comment by guidupuy** [comment]
As a matter of fact, I am! That’s weird...

**Comment by atomiks** [comment]
Make sure you run `npm i @tippy.js/react@latest` (or Yarn equiv) to pull in the latest `tippy.js`. Make sure it's resolving to the latest one (5.1.3)

**Comment by guidupuy** [comment]
Will do, thanks.

**Comment by guidupuy** [comment]
```
MacBook-Pro-de-Guillaume-2:afiniti-bottle guillaumedupuy$ npm view tippy.js version
5.1.3
MacBook-Pro-de-Guillaume-2:afiniti-bottle guillaumedupuy$ npm view @tippy.js/react version
3.1.1
```
... And yet I do get `x-placement` attributes on my `.tippy-tooltip` elements and no auto `appendTo={'parent'}` for nested tippies.

**Comment by guidupuy** [comment]
Even the tippies on the Tippy.js website has `x-placement`... unless I'm missing something?

<img width="708" alt="Screen Shot 2020-01-13 at 9 49 57 AM" src="https://user-images.githubusercontent.com/1026103/72242626-2b1a8880-35ea-11ea-88ac-d4e03a810e9e.png">

**Comment by atomiks** [comment]
`x-placement` is only on `.tippy-popper` since that's what Popper's `applyStyle` modifier does. But Tippy adds `data-placement` to the child, the actual tooltip, `.tippy-tooltip` to align with the other attributes.

Look in node_modules for tippy.js/dist/tippy.css and see if there's child selectors, or `console.log(tippy.version)` (runtime) to make sure you're not using a diff version 🤷‍♂

**Comment by guidupuy** [comment]
Ok I feel like a complete idiot. `npm view x version` doesn't show the installed version but the latest available one. I am indeed not on the latest version... Sorry for all this!

**Comment by chris-baytek** [comment]
Hey atomik.  Is this still the way to nest?  I'm looking to create a simple dropdown and the nested items are not showing up using data-template="", I have not tryed the above yet as I thought nesting was already included.

**Comment by git765** [comment]
This nesting

> This is the repo for the React wrapper not the vanilla lib 
> 
> Anyway, I'm not really sure what your code is supposed to be doing, but you the inner elements need to be part of a content element for the main parent tippy.
> 
> ```js
> const content = document.createElement('div')
> 
> // 3 inner buttons with their own tippy
> for (let i = 0; i < 3; i++) {
>   const button = document.createElement('button')
>   button.textContent = 'Text'
>   content.appendChild(button)
> 
>   tippy(button, {
>     content: "I'm a Tippy tooltip!",
>   })
> }
> 
> tippy('.myTip3', {
>   content,
> })
> ```
> 
> Extra logic is required to handle an edge case related to the parent tippy hiding which causes the child tippy to become disjointed from its reference element if it was also showing.... I'm going to document it soon

Does not work on the last version (5). Do you have a solution for the new version?
