### ISSUE TITLE
Passing HTML content doesn't work

### ISSUE THREAD

**Issue by krulik** [atomiks/tippy.js-react#94]
It seems that in the React version of Tippy it's impossible to parse the content as HTML.

I've created two Code Sandboxes to demonstrate:
React Tippy: https://codesandbox.io/s/reacttippy-mr12h
Vanilla Tippy: https://codesandbox.io/s/tippyhtml-e12og

Am I missing something? Quite new to React, tried to Google but only solution I've found was using a parse library to turn the string into JSX.

**Comment by atomiks** [comment]
Yeah you should use JSX instead. In this React wrapper, it just renders the (literal) string into a container element, which will never get parsed as HTML. Also, writing/reading HTML as a string is not very nice DX anyway, so it's good to avoid it when possible

```jsx
<Tippy
  content={
    <>
      Hello <b>html</b>
    </>
  }
>
  <button>My button</button>
</Tippy>
```

**Comment by krulik** [comment]
Thanks, I get it.
I think it deserves a section in the React port documentation, cause it breaks the vanilla version API.
I'll use an external parse to JSX library, since I have exactly this use case where I get the HTML as a string.

**Comment by atomiks** [comment]
Why not `dangerouslySetInnerHTML`

```jsx
<Tippy content={<div dangerouslySetInnerHTML={{__html: string}} />>
  <button>My button</button>
</Tippy>
```

**Comment by krulik** [comment]
@atomiks Thanks !!! Saw it but didn't make the connection of how to use it, very helpful.

**Comment by eythort-mm** [comment]
First of all, since this is different to how the vanilla version works, with allowHTML defaulted to true there, this needs to be clearly documented in the react port, that allowHTML is ignored and always false. Also, this used to work in an earlier version of tippy-react, but doesn't with the latest version. 
The workaround is easy, but nevertheless, it needs to be documented
