### ISSUE TITLE
Getting error while passing element to appendTo in tippy

### ISSUE THREAD

**Issue by nidhinkumar06** [atomiks/tippy.js-react#95]
I have tried to pass an element to appendTo  but when the application runs i am getting the following error.
![HawkEye (5)](https://user-images.githubusercontent.com/10459220/58694732-5b8e1900-83b1-11e9-9959-d8211e09747b.jpg)

I would like to know whether i am doing it in the correct way or not.I tried to put the console where it shows the DOM hierarchy.

Code:

```
<Tippy
        content={
          <div>
            <h5>{clusterId}</h5>
            <p>Total Devices: {totalNodes}</p>
            <hr style={{ borderColor: 'white' }} />
            <ol style={{ textAlign: 'left', paddingLeft: '10pt' }}>
              <li>Good: {good}</li>
              <li>Need Attention: {attention}</li>
              <li>Monitor Closely: {monitor}</li>
            </ol>
          </div>
        }
        appendTo={document.getElementById('mapview')}
        arrow={true}
        animation="fade"
        theme="bootstrap"
        duration={0}
        placement="auto"
        hideOnClick={false}
      >
        <div
          className="pin bounce"
          style={{ backgroundColor: color, cursor: 'pointer' }}
          onClick={handleClick}
        />
      </Tippy>
```

**Comment by atomiks** [comment]
Well it looks like a TypeScript error because the element could potentially be `null` which will cause a runtime error. So you could either use type assertion `as Element` if you're 100% sure the `getElementById` call will work, or better use a ref to pass the node instead

**Comment by KubaJastrz** [comment]
^ Correct. In TypeScript with `strictNullChecks`, `document.getElementById` type definition looks like this:
```ts
Document.getElementById(elementId: string): HTMLElement | null
```

Technically, you can never be sure if `elementId` will be found, so that's why the `null` is here. You can override it this way:
```
appendTo={document.getElementById('mapview')!}
```
Or make a fallback to some other element.
