### ISSUE TITLE
Use props instead of options

### ISSUE THREAD

**Issue by fritzlolpro** [atomiks/tippy.js-react#97]
Hello!
Really enjoying using your library, nice work!.
Found some issue, in my code I use tippy like:
````
import Tippy from '@tippy.js/react'

const StyledMenuTippyDropdown = styled(Tippy)
    *some irrelevant styling*


<StyledMenuTippyDropdown
        content={<ProjectMenu {...props} />}
        arrow
        trigger="click"
        animation="scale"
        duration={0}
        delay={[300, 0]}
        theme="light"
        interactive
    >
        <MenuIconWrapper>
            <NineSquare viewBox="0 0 612 612" width="24" height="24" />
        </MenuIconWrapper>
    </StyledMenuTippyDropdown>
````

When I click on some interactive object inside my tippy I get an error

> Uncaught TypeError: Cannot read property 'interactive' of undefined

I've tried to make some investigation and found that on some stage the code refers to 
**popper._tippy.options.interactive**
while the correct data is in 
**popper._tippy.props.interactive**

pic included
[https://api.monosnap.com/file/download?id=8Mh0CwHBWpoSWcMlLs6ODifz526yM1](url)
![image](https://user-images.githubusercontent.com/10850158/58964572-d1322480-87b7-11e9-8623-63452d0f5cab.png)

Maybe it could be fixed by just adding popper._tippy.props.interactive to the condition check.

If so I can do it by myself and then make a pull request. 

But probably made some mistakes while working with tippy and it's not a bug but only my stupidness :-)

Anyway I'm looking for help with this issue, thanks!

**Comment by atomiks** [comment]
That looks like a **really** old version of `tippy.js` actually. Like v2 instead of v4. Which means something else is requiring the old version but two versions of `tippy.js` breaks things because of the global listeners.

You can check your package-lock/yarn.lock to see why that is happening

**Comment by fritzlolpro** [comment]
Could this happen if I'm using react-tippy for developing some module that builds and operates separately and used inside couple of others big projects which probably has tippy.js of older versions but I cant affect this. Is there is a way to encapsulate my nice new tippy from theirs old-buggy? 

 My library is using "tippy.js": "^4.3.0"

**Comment by KubaJastrz** [comment]
`react-tippy` is practically deprecated at this point, since we have an official `@tippy.js/react` and it was always out-of-date, because didn't use `tippy.js` npm package but rather copied the source code and stopped maintaining it.

It could be possible that when using both packages the `tippy` namespace gets overridden and this happens, but it won't show up in the `*.lock` files.

**Comment by atomiks** [comment]
> Is there is a way to encapsulate my nice new tippy from theirs old-buggy?

Don't know why this is so funny 😆 

---

Yeah that's like... v1 I think? 😬

`react-tippy` & `@tippy.js/react` are being bundled together on the page where the error occurs. Hopefully you can find out how that's happening, but it's not an error with this library at least 🙂

**Comment by fritzlolpro** [comment]
Ok, thanks, will try to fix it for my projects by myself with some razor and duct tape :-)
