### ISSUE TITLE
Question - Programmatically create tippies on spans inserted with 'dangerouslySetInnerHTML'

### ISSUE THREAD

**Issue by paulincai** [atomiks/tippy.js-react#98]
Hi,
I was wondering whether there would be any way to attach tippies to selectors inserted with ```dangerouslySetInnerHTML```. This is used for example when you have HTML saved in the DB and you want to push it in the DOM.

My example:
HTML (coming from DB): ```const caption = '<span class="hashtag">#bentley</span>'```
JSX in React:  ```<div dangerouslySetInnerHTML={caption} />```
(https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml)

I want to attach the Tippy to the span so that when I hover over #bentley, I get some options.

Thank you,
Paul

**Comment by atomiks** [comment]
I don't think you'd be able to use the `<Tippy />` component which expects a React element as a child. You can import the underlying [`tippy`](https://atomiks.github.io/tippyjs/creating-tooltips/) function though:

```js
import {tippy} from '@tippy.js/react';
```

You can use this to apply the tippy in a `useEffect` + use the span's CSS selector

**Comment by paulincai** [comment]
That worked great. Just to add to this for the sake of sharing some experience, when you do this in React and you want to pass content as HTML, you can/need to write JSX and wrap it with 'renderToString' like so:
```
import ReactDOMServer from 'react-dom/server'

const contentBeforePassToTippy = (
   ... JSX with onClick on elements, etc
)
content = ReactDOMServer.renderToString(contentBeforePassToTippy) // this is for tippy(element, options)
```
If you use simple HTML for content, you can pass HTML as as string but getting click events results in adding a lot of overhead when they can easily be written into JSX and "converted" to HTML.
It works really great, truly better than expected.
